### ISSUE TITLE
Create video using images.

### ISSUE THREAD

**Issue by JeetChaudhary** [jcodec/jcodec#102]
Hi, I have a issue regarding to this, i am creating video using images, but I think it have some problems. can you please help me out this. I am using this code.

 SequenceEncoder se;
            try {
                se = new SequenceEncoder(new File(ExternalPaths.mEffectPath + "MyMp3.mp4"));
                se.encodeImage(Utils.decodeBitmap(uri, context));
                se.finish();
              } catch (IOException e) {
                     e.printStackTrace();
            }
Am I doing it properly. Please tell me. 

Is there othere way to achieve this?
Thanks.

**Comment by svitvitskiy** [comment]
What kind of problem do you have?

Do you get an exception? If so, could you post a stack trace? Or the file
is not encoded correctly? If so then please upload the file and share the
link with me.

Thanks!

Stan

**Comment by JeetChaudhary** [comment]
I didn't get any exception Sir, It encoding properly. But the duration of movie is very short. Its about 00:00 Second. Can I set time duration for the movie? Like I want to create a movie of 1:00 minute. How can I achieve this? Please help me out Sir.
Thanks.

**Comment by svitvitskiy** [comment]
Ok, so you would need to set longer frame duration for this.

You will probably need to use lower level API. Please have a look at:
https://github.com/jcodec/jcodec/blob/master/samples/main/java/org/jcodec/samples/transcode/TranscodeMain.java

'prores2avc' method.

Stan

**Comment by JeetChaudhary** [comment]
Thanks for replying Sir, I want to achieve this in Android platform. But I think android doesn't support import java.awt.image.BufferedImage;

So how can I implement this class in Android? 
Is there any implemented code for android platform?

thanks..

**Comment by JeetChaudhary** [comment]
App is crashing when I adding multiple images in: 
sequenceEncoder.encodeNativeFrame(Bitmap);

12-02 17:50:58.802  12601-12747/com.example.recordandeffetcts E/AndroidRuntime﹕ FATAL EXCEPTION: AsyncTask #1
    java.lang.RuntimeException: An error occured while executing doInBackground()
            at android.os.AsyncTask$3.done(AsyncTask.java:299)
            at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:352)
            at java.util.concurrent.FutureTask.setException(FutureTask.java:219)
            at java.util.concurrent.FutureTask.run(FutureTask.java:239)
            at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
            at java.lang.Thread.run(Thread.java:838)
     Caused by: java.lang.ArrayIndexOutOfBoundsException: length=24000; index=24198
            at org.jcodec.scale.RgbToYuv420j.rgb2yuv(RgbToYuv420j.java:72)
            at org.jcodec.scale.RgbToYuv420j.transform(RgbToYuv420j.java:38)
            at org.jcodec.api.SequenceEncoder.encodeNativeFrame(SequenceEncoder.java:72)
            at com.example.recordandeffetcts.fragment.RecordSoundFragment.makeMovie(RecordSoundFragment.java:278)
            at com.example.recordandeffetcts.fragment.RecordSoundFragment$VideoTask.doInBackground(RecordSoundFragment.java:610)
            at com.example.recordandeffetcts.fragment.RecordSoundFragment$VideoTask.doInBackground(RecordSoundFragment.java:589)
            at android.os.AsyncTask$2.call(AsyncTask.java:287)
            at java.util.concurrent.FutureTask.run(FutureTask.java:234)
            at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
            at java.lang.Thread.run(Thread.java:838)


Its throwing at.. 
transform.transform(pic, toEncode);

Any help will be appreciate...

**Comment by MMasterson** [comment]
@JeetChaudhary 
I've solved this issue myself by basically taking the Android Sequence Recorder class, and copying it to modify.

```java
package YOUR.PACKAGE.HERE

import org.jcodec.codecs.h264.H264Encoder;
import org.jcodec.codecs.h264.H264Utils;
import org.jcodec.common.NIOUtils;
import org.jcodec.common.SeekableByteChannel;
import org.jcodec.common.model.ColorSpace;
import org.jcodec.common.model.Picture;
import org.jcodec.common.model.TapeTimecode;
import org.jcodec.containers.mp4.Brand;
import org.jcodec.containers.mp4.MP4Packet;
import org.jcodec.containers.mp4.TrackType;
import org.jcodec.containers.mp4.muxer.FramesMP4MuxerTrack;
import org.jcodec.containers.mp4.muxer.MP4Muxer;
import org.jcodec.scale.ColorUtil;
import org.jcodec.scale.Transform;

import java.io.File;
import java.io.IOException;
import java.nio.ByteBuffer;
import java.util.ArrayList;

/**
 * Created by Mark R. Masterson on 12/8/15.
 *Original @author The JCodec project
 */
public class SequenceEncoder2 {
    private SeekableByteChannel ch;
    private Picture toEncode;
    private Transform transform;
    private H264Encoder encoder;
    private ArrayList<ByteBuffer> spsList;
    private ArrayList<ByteBuffer> ppsList;
    private FramesMP4MuxerTrack outTrack;
    private ByteBuffer _out;
    private int frameNo;
    private MP4Muxer muxer;

    public SequenceEncoder2(File out) throws IOException {
        this.ch = NIOUtils.writableFileChannel(out);

        // Muxer that will store the encoded frames
        muxer = new MP4Muxer(ch, Brand.MP4);

        // Add video track to muxer
        outTrack = muxer.addTrack(TrackType.VIDEO, 25);

        // Allocate a buffer big enough to hold output frames
        _out = ByteBuffer.allocate(1920 * 1080 * 6);

        // Create an instance of encoder
        encoder = new H264Encoder();

        // Transform to convert between RGB and YUV
        transform = ColorUtil.getTransform(ColorSpace.RGB, encoder.getSupportedColorSpaces()[0]);

        // Encoder extra data ( SPS, PPS ) to be stored in a special place of
        // MP4
        spsList = new ArrayList<ByteBuffer>();
        ppsList = new ArrayList<ByteBuffer>();

    }

    public void encodeNativeFrame(Picture pic) throws IOException {
        if (toEncode == null) {
            toEncode = Picture.create(pic.getWidth(), pic.getHeight(), encoder.getSupportedColorSpaces()[0]);
        }

        // Perform conversion
        transform.transform(pic, toEncode);

        // Encode image into H.264 frame, the result is stored in '_out' buffer
        _out.clear();
        ByteBuffer result = encoder.encodeFrame(toEncode, _out);

        // Based on the frame above form correct MP4 packet
        spsList.clear();
        ppsList.clear();
        H264Utils.wipePS(result, spsList, ppsList);
        H264Utils.encodeMOVPacket(result);

        // Add packet to video track
        //ByteBuffer data, long pts, long timescale, long duration, long frameNo, boolean iframe,TapeTimecode tapeTimecode, long mediaPts, int entryNo
        //If you want the video to play slowly set small timescale and large frame duration. Say timescale=1, duration=5 will show 1 frame every 5 seconds.
        outTrack.addFrame(new MP4Packet(result, frameNo, 25, 20, frameNo, true, null, frameNo, 0));

        frameNo++;
    }

    public void finish() throws IOException {
        // Push saved SPS/PPS to a special storage in MP4
        outTrack.addSampleEntry(H264Utils.createMOVSampleEntry(spsList, ppsList, 4));

        // Write MP4 header and finalize recording
        muxer.writeHeader();
        NIOUtils.closeQuietly(ch);
    }
}
```

as you can see from the line
```java
 // Add packet to video track
        //ByteBuffer data, long pts, long timescale, long duration, long frameNo, boolean iframe,TapeTimecode tapeTimecode, long mediaPts, int entryNo
        //If you want the video to play slowly set small timescale and large frame duration. Say timescale=1, duration=5 will show 1 frame every 5 seconds.
        outTrack.addFrame(new MP4Packet(result, frameNo, 25, 20, frameNo, true, null, frameNo, 0));
```

it gives a detailed description on how the timescale and FPS works. 

You might also notice that this <b>DOES NOT</b>  accept Bitmap, but a Picture object

Here are two methods for converting a Bitmap to a Picture object native to JCodec
````java
 public static Picture fromBitmap(Bitmap src) {
        Picture dst = Picture.create((int) src.getWidth(), (int) src.getHeight(), ColorSpace.RGB );
        fromBitmap(src, dst);
        return dst;
    }

    public static void fromBitmap(Bitmap src, Picture dst) {
        int[] dstData = dst.getPlaneData(0);
        int[] packed = new int[src.getWidth() * src.getHeight()];

        src.getPixels(packed, 0, src.getWidth(), 0, 0, src.getWidth(), src.getHeight());

        for (int i = 0, srcOff = 0, dstOff = 0; i < src.getHeight(); i++) {
            for (int j = 0; j < src.getWidth(); j++, srcOff++, dstOff += 3) {
                int rgb = packed[srcOff];
                dstData[dstOff] = (rgb >> 16) & 0xff;
                dstData[dstOff + 1] = (rgb >> 8) & 0xff;
                dstData[dstOff + 2] = rgb & 0xff;
            }
        }
    }
````

**Comment by MMasterson** [comment]
@JeetChaudhary  still having trouble?

**Comment by ciprianpop** [comment]
For the problem encountered by @JeetChaudhary , the cause lies in the fact that the toEncode image has other dimensions that _pic_ image.

Solution:
b = <... get bitmap at desired resolution>
b = Bitmap.createScaledBitmap(b, targetWidth, targetHeight, true);// this line solves the issue at hand recreating the bitmap; make sure targetWidth and targetHeight are the same for _pic_ and _toEncode_
transform.encodeNativeFrame(b);
