### ISSUE TITLE
HTML5 <video> tag viewing

### ISSUE THREAD

**Issue by simonkramer** [jcodec/jcodec#103]
Hi Stan,

I use 
	
SequenceMuxer muxer = new SequenceMuxer(new File(movfilepathstr));
muxer.encodeImage(new File(framefilepathstr));

to create a movie from PNG-files (framefilepathstr), which then 
successfully loads (with an M4V-suffix but not with a MOV-suffix) in 

- QuickTime 7 (latest), directly, and in
- QuickTime 10 (latest), indirectly, that is, by a transformation into 
  an MOV-file, which QuickTime 10 automatically performs.

However, the movie does not load in the HTML5 <video> tag

http://www.w3schools.com/tags/tag_video.asp

with type="video/mp4", although it really should 

https://en.wikipedia.org/wiki/M4V

at least with an MP4-suffix.

Please, how can I use your library to generate a movie 
from PNG-files that does load in an HTML5 <video> tag?

Many thanks and best regards,

	— Simon

**Comment by svitvitskiy** [comment]
Simon,

I think your web browser most probably expects to find H264 video inside
the mp4 container and not the png images, though quicktime supports it it
really is player specific.

I'd recommend you use SequenceEncoder class which actually transcodes your
frames into a simplistic H264 i-frame only stream.

Stan

**Comment by simonkramer** [comment]
Hi Stan,

Thanks, that works, but the frame quality is very bad and the movie plays much too fast.
Is there a simple way to tune the quality as well as the play duration of the frames?
My wish would be a SequenceEncoder-constructor with these two parameters.

Many thanks,
Simon

**Comment by svitvitskiy** [comment]
You can pass an instance of RateControl to the constructor. Just extend
this class and make it return lower QP.

The quality is something I've been asked about a lot. So I'll be looking at
it. Right now you just need to throw more bits at it, i.e. lower the QP.

The frame rate can be controlled if you slightly change the SequenceEncoder
class. Right now this option isn't in the API.

Stan

**Comment by simonkramer** [comment]
Done, but:
With a lower QP (2, 1, or 0) it only gets much worse, and 
with a higher QP (32) it does not get better.
(With a QP of 64, I get the run time error "java.lang.IllegalArgumentException: Max 32 bit to write".)

MyRateControl code snippet (example QP):
private static final int QP = 2;

MySequenceEncoder code snippet:
encoder = new H264Encoder(new MyRateControl());

**Comment by svitvitskiy** [comment]
Well, the QP should be anything between 12 and 36.

Also could you post your videos so I can see what do you mean by bad
quality? Maybe there is a bug somewhere that I am not aware of.

Stan

**Comment by simonkramer** [comment]
Hi Stan,

I will send you video material, but before there is a bug to correct (different and more important):

java.lang.IllegalArgumentException: Component 1 width should be a multiple of 2 for colorspace: YUV420J
	at org.jcodec.common.model.Picture8Bit.<init>(Picture8Bit.java:42)
	at org.jcodec.common.model.Picture8Bit.create(Picture8Bit.java:83)
	at org.jcodec.common.model.Picture8Bit.fromPicture(Picture8Bit.java:178)
	at org.jcodec.codecs.h264.H264Encoder.encodeFrame(H264Encoder.java:92)
	at rex.MySequenceEncoder.encodeNativeFrame(MySequenceEncoder.java:91)

The critical code snippet is:

Picture pic = AWTUtil.fromBufferedImage(ImageIO.read(framefile));
try { mysequenceencoder.encodeNativeFrame(pic); } 
catch (Exception e)

Please consider the attached file with the MySequenceEncoder-class, which I adapted from 
your code following your suggestion (Line 27 and 67; maybe other folks are interested too):

[MySequenceEncoder.txt](https://github.com/jcodec/jcodec/files/69511/MySequenceEncoder.txt)

Note that the throwing of the above exception is platform-dependent (!):
- it is NOT thrown on my MacBookPro (Java 1.8.0) for any picture, but 
- it IS thrown on my Ubuntu vserver (Java 1.8.0) for some pictures (size seems to matter).

Maybe the following link is relevant for correcting this (graphics-related) bug:
http://www.oracle.com/technetwork/articles/javase/headless-136834.html

Thanks and best regards,

Simon

**Comment by svitvitskiy** [comment]
Simon,

Thank you for letting me know, just to check, could you log the sizes of
your pictures and make sure both their width and height are even (multiple
of 2)?
This error message is non obvios but it's saying that you are trying to
encode a picture with one or both dimensions beeing an odd number.
If you believe this is never the case please let me know. Also it would
help alot if you could provide a java testcase that reliably reproduces
this situation.

Stan

**Comment by simonkramer** [comment]
Hi Stan,

OK, ensuring evenness (cropping) is a solution, but IMHO a sub-optimal one.

Concerning sub-optimal frame quality, please consider the following video material:

https://www.rule-extractor.ch/movies/DevRandom_0.mp4

where you can see patches of artefact pink washing out squares of crisp colours in 
Frame 5 - Frame 24, and this with your QP = 12 (best quality, if I understood you correctly).

Please, would it be possible to get rid of this pink?

Best,

Simon.

**Comment by arpitcybernetyx** [comment]
Just make sure width and height are even integers . If not  do ((int)width/2)*2 . It will work

**Comment by s366315** [comment]
> Just make sure width and height are even integers . If not do ((int)width/2)*2 . It will work

exact your image width and height should be multiple by 2
