### ISSUE TITLE
Error - Grabbing a frame using FrameGrab

### ISSUE THREAD

**Issue by stuts** [jcodec/jcodec#111]
Hi,

I am using FrameGrab class from "org.jcodec.api.awt" package and the code for grabbing a single frame is as follows:

int frameNumber = 30;
BufferedImage frame = FrameGrab.getFrame(new File(filePath + fileName), frameNumber);
ImageIO.write(frame, "png", new File(filePath + "frame_150.png"));

When I run the above code, I am getting following error(s):

[ERROR   ] SRVE0777E: Exception thrown by application class 'org.jcodec.api.awt.FrameGrab.getFrame:102'
java.lang.NoSuchMethodError: org.jcodec.common.NIOUtils.closeQuietly(Ljava/io/Closeable;)V
	at org.jcodec.api.awt.FrameGrab.getFrame(FrameGrab.java:102)
	at com.vs.controllers.UploadFile.doPost(UploadFile.java:104)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.service(ServletWrapper.java:1287)
	at [internal classes]

Can anyone tell me how to fix the above errors?

**Comment by toddjmorgan** [comment]
I'm having the same issue.

**Comment by fatbatman** [comment]
same

**Comment by svitvitskiy** [comment]
The NIOUtils class has been moved into a sub-package called 'io'. So you will need to clean your artifacts in order for this to work.
Are you getting your artifacts from the repository or are you building from HEAD?

**Comment by svitvitskiy** [comment]
Please try it now, the package error has been fixed.

**Comment by AlbertoCrespoGuzman** [comment]
same here

**Comment by AlbertoCrespoGuzman** [comment]
Same error here, seems that it is not solved.

**Comment by svitvitskiy** [comment]
Please try the latest version from git and use the class AWTFrameGrab8Bit.

Stan

**Comment by romainlefebvre** [comment]
I confirm that it works with the latest version from git.
You must install it in your local repo then add this dependency:

		<dependency>
			<groupId>org.jcodec</groupId>
		  	<artifactId>jcodec-javase</artifactId>
		  	<version>0.2.0</version>
		</dependency>

@svitvitskiy You should release this version in Maven Central.

Thanks,
Romain

**Comment by AlbertoCrespoGuzman** [comment]
Sorry I have some problem adding this dependency. Could you please update the .JAR files 2.0 in the github? Thanks

**Comment by hseshadr** [comment]
Hi Stan,

Thanks for this project it looks very promising. I downloaded the jar from git and still have the same error. I agree with romainlefebvre that perhaps you could upload the dependency .
    <dependency>
        <groupId>org.jcodec</groupId>
        <artifactId>jcodec-javase</artifactId>
        <version>0.2.0</version>
    </dependency>

**Comment by AlbertoCrespoGuzman** [comment]
How to save the Picture8bit as a image? I can not do that with the ImageIO.write ...

**Comment by rachoac** [comment]
Can we please publish this to maven central?

**Comment by fahadtasleem** [comment]
I am unable to get version 0.2.0 from maven. Can you please publish it

**Comment by roroco** [comment]
I have a tmp solution,  NIOUtils.closeQuietly is in org.jcodec:jcodec:0.1.9, in my build.gradle

```
dependencies {
  ...
      compile 'org.jcodec:jcodec:0.1.9'
      compile 'org.jcodec:jcodec-javase:0.1.9'
...
}
```

and following code will work:
```
class TestJCodec {
    static void main(String[] args) {
        new TestJCodec().st()
    }

    void st() {
        double msec = 10000
        BufferedImage frame = getFrame(new File(Env.down("test.mp4")), msec / 1000);
        ImageIO.write(frame, "jpg", new File("/tmp/test.jpg"));
    }

    BufferedImage getFrame(File file, double sec) {
        FileChannelWrapper ch = null;
        try {
            ch = NIOUtils.readableFileChannel(file);
            return ((FrameGrab) new FrameGrab(ch).seekToSecondPrecise(sec)).getFrame();
        } finally {
            NIOUtils.closeQuietly(ch);
        }
    }
}

```

**Comment by bahtiyarerden** [comment]
Hello i am still getting this error. I am trying to use 0.1.9 version. Can you put 0.2.0 version to the maven central?
