### ISSUE TITLE
ArrayIndexOutOfBoundsException when trying to getFrame() of high res video

### ISSUE THREAD

**Issue by vxhviet** [jcodec/jcodec#129]
Hi jcodec Developers,
I would like to thanks you guys for your awesome work. How ever I'm currently having a crash when trying to `getFrame()` from 1080p videos produced by the Galaxy S6, (works fine with 720p vids produced by the Nexus 5).
I would be awesome if you guys can take a minute to look into this.
My code snippet:
```java
FileChannelWrapper ch = null;
try {
      File file = new File(mVideoPath);
      ch = NIOUtils.readableFileChannel(file);
      FrameGrab fg = new FrameGrab(ch);
      fg.seekToFramePrecise((int)(currentPosition*29.851/1000)); //fixed fps is for testing purpose

      Bitmap bitmap = fg.getFrame();
      return bitmap;
}catch (IOException ex) {
       ex.printStackTrace();
} catch (JCodecException ex) {
       ex.printStackTrace();
}  finally {
        NIOUtils.closeQuietly(ch);
}
```

Error stack trace:
```
FATAL EXCEPTION: main
Process: com.example.viet.myappdemo, PID: 13290
java.lang.ArrayIndexOutOfBoundsException: length=345600; index=345600
     at org.jcodec.scale.BitmapUtil.toBitmap(BitmapUtil.java:61)
     at org.jcodec.scale.BitmapUtil.toBitmap(BitmapUtil.java:51)
     at org.jcodec.common.AndroidUtil.toBitmap(AndroidUtil.java:29)
     at org.jcodec.api.android.FrameGrab.getFrame(FrameGrab.java:88)
     at com.example.viet.myappdemo.VideoActivity.getFrame(VideoActivity.java:280)
     at com.example.viet.myappdemo.VideoActivity.access$100(VideoActivity.java:43)
     at com.example.viet.myappdemo.VideoActivity$2.run(VideoActivity.java:245)
     at android.os.Handler.handleCallback(Handler.java:739)
     at android.os.Handler.dispatchMessage(Handler.java:95)
     at android.os.Looper.loop(Looper.java:145)
     at android.app.ActivityThread.main(ActivityThread.java:6837)
     at java.lang.reflect.Method.invoke(Native Method)
     at java.lang.reflect.Method.invoke(Method.java:372)
     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
```

**Comment by svitvitskiy** [comment]
Please post your video so I can reproduce.

**Comment by vxhviet** [comment]
Hi @svitvitskiy, thank you very much for your prompt response. Surprisingly I do not have this crashing on the Galaxy s6 anymore (same code, same video), however it still crash on the Nexus 5. The said 1080p can be obtained via [Dropbox](https://www.dropbox.com/s/u9r3vds7ucg3nug/20160331_164425.mp4?dl=0) 

This particular low resolution video [Dropbox](https://www.dropbox.com/s/nolffy73aj4rvvi/documentariesandyou.mp4?dl=0) crash on both devices with this stack trace:
```
FATAL EXCEPTION: main
Process: com.example.viet.myappdemo, PID: 25154
java.lang.ArrayStoreException: org.jcodec.containers.mp4.boxes.LeafBox cannot be stored in an array of type org.jcodec.containers.mp4.boxes.SampleEntry[]
 at java.util.LinkedList.toArray(LinkedList.java:958)
 at org.jcodec.containers.mp4.boxes.Box.findAll(Box.java:83)
 at org.jcodec.containers.mp4.boxes.Box.findFirst(Box.java:49)
 at org.jcodec.containers.mp4.demuxer.MP4Demuxer.processHeader(MP4Demuxer.java:68)
 at org.jcodec.containers.mp4.demuxer.MP4Demuxer.findMovieBox(MP4Demuxer.java:62)
 at org.jcodec.containers.mp4.demuxer.MP4Demuxer.<init>(MP4Demuxer.java:50)
 at org.jcodec.api.FrameGrab.<init>(FrameGrab.java:75)
 at org.jcodec.api.android.FrameGrab.<init>(FrameGrab.java:40)
 at com.example.viet.myappdemo.VideoActivity.getFrame(VideoActivity.java:275)
 at com.example.viet.myappdemo.VideoActivity.access$100(VideoActivity.java:43)
 at com.example.viet.myappdemo.VideoActivity$2.run(VideoActivity.java:245)
 at android.os.Handler.handleCallback(Handler.java:739)
 at android.os.Handler.dispatchMessage(Handler.java:95)
 at android.os.Looper.loop(Looper.java:148)
 at android.app.ActivityThread.main(ActivityThread.java:5417)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

Another thing, I understand this is currently a limitation, but the extraction time on the Nexus 5 is painfully slow (more than a minute). Is there anything I can do to improve the performance?

Thank you very much for your time.

**Comment by svitvitskiy** [comment]
Just tried on the latest jcodec from HEAD. Seems to be working, could you try?

git clone https://github.com/jcodec/jcodec.git
cd jcodec; mvn clean install; cd android; mvn clean install;

You will have jcodec-0.2.0.jar and jcodec-android-0.2.0.jar in your local maven repo.

Then simply add 'mavenLocal()' to your build.gradle repositories section, like here:
https://github.com/jcodec/jcodec/blob/master/android/sample/build.gradle

**Comment by vxhviet** [comment]
Hi, 
Thank you very much for your quick response. 
I have a problem, previously `FrameGrab`, `FileChannelWrapper` and `NIOUtils` come from:
```java
import org.jcodec.api.android.FrameGrab;
import org.jcodec.common.FileChannelWrapper;
import org.jcodec.common.NIOUtils;
``` 
In jcodec-android-0.2.0 it seem like the only available one is `AndroidFrameGrab8Bit` as `AndroidFrameGrab` has been marked as deprecated. However they both take `SeekableDemuxerTrack, ContainerAdaptor` for their constructor. Would you mind provide a quick example of how to use this new `AndroidFrameGrab8Bit` ?

**Comment by svitvitskiy** [comment]
Yep, you just go AndroidFrameGrab8Bit.createAndroidFrameGrab8Bit(
SeekableByteChannel in)

**Comment by vxhviet** [comment]
Dear @svitvitskiy, thank you so much for your assists, 

I still have some what similar issue. The high res video doesn't crash anymore on the Nexus 5, however the low res video still crashing with this stack trace:

```
FATAL EXCEPTION: main
		Process: com.example.viet.myappdemo, PID: 32001
		java.lang.RuntimeException: java.lang.NoSuchMethodException: <init> [class org.jcodec.containers.mp4.boxes.Header]
			at org.jcodec.platform.Platform.newInstance(Platform.java:23)
			at org.jcodec.containers.mp4.BoxFactory.newBox(BoxFactory.java:49)
			at org.jcodec.containers.mp4.boxes.Box.parseBox(Box.java:111)
			at org.jcodec.containers.mp4.boxes.NodeBox.parseChildBox(NodeBox.java:62)
			at org.jcodec.containers.mp4.boxes.NodeBox.parse(NodeBox.java:47)
			at org.jcodec.containers.mp4.boxes.Box.parseBox(Box.java:114)
			at org.jcodec.containers.mp4.boxes.NodeBox.parseChildBox(NodeBox.java:62)
			at org.jcodec.containers.mp4.boxes.NodeBox.parse(NodeBox.java:47)
			at org.jcodec.containers.mp4.boxes.Box.parseBox(Box.java:114)
			at org.jcodec.containers.mp4.boxes.NodeBox.parseChildBox(NodeBox.java:62)
			at org.jcodec.containers.mp4.boxes.NodeBox.parse(NodeBox.java:47)
			at org.jcodec.containers.mp4.BoxUtil.parseBox(BoxUtil.java:16)
			at org.jcodec.containers.mp4.MP4Util$Atom.parseBox(MP4Util.java:148)
			at org.jcodec.containers.mp4.MP4Util.parseMovieChannel(MP4Util.java:65)
			at org.jcodec.containers.mp4.demuxer.MP4Demuxer.findMovieBox(MP4Demuxer.java:54)
			at org.jcodec.containers.mp4.demuxer.MP4Demuxer.<init>(MP4Demuxer.java:46)
			at org.jcodec.api.FrameGrab8Bit.createFrameGrab8Bit(FrameGrab8Bit.java:52)
			at org.jcodec.api.android.AndroidFrameGrab8Bit.createAndroidFrameGrab8Bit(AndroidFrameGrab8Bit.java:42)
			at com.example.viet.myappdemo.VideoActivity.getFrame(VideoActivity.java:280)
			at com.example.viet.myappdemo.VideoActivity.access$100(VideoActivity.java:45)
			at com.example.viet.myappdemo.VideoActivity$2.run(VideoActivity.java:247)
			at android.os.Handler.handleCallback(Handler.java:739)
			at android.os.Handler.dispatchMessage(Handler.java:95)
			at android.os.Looper.loop(Looper.java:148)
			at android.app.ActivityThread.main(ActivityThread.java:5417)
			at java.lang.reflect.Method.invoke(Native Method)
			at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
			at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
		 Caused by: java.lang.NoSuchMethodException: <init> [class org.jcodec.containers.mp4.boxes.Header]
			at java.lang.Class.getConstructor(Class.java:528)
			at java.lang.Class.getConstructor(Class.java:492)
			at org.jcodec.platform.Platform.newInstance(Platform.java:21)
			at org.jcodec.containers.mp4.BoxFactory.newBox(BoxFactory.java:49) 
			at org.jcodec.containers.mp4.boxes.Box.parseBox(Box.java:111) 
			at org.jcodec.containers.mp4.boxes.NodeBox.parseChildBox(NodeBox.java:62) 
			at org.jcodec.containers.mp4.boxes.NodeBox.parse(NodeBox.java:47) 
			at org.jcodec.containers.mp4.boxes.Box.parseBox(Box.java:114) 
			at org.jcodec.containers.mp4.boxes.NodeBox.parseChildBox(NodeBox.java:62) 
			at org.jcodec.containers.mp4.boxes.NodeBox.parse(NodeBox.java:47) 
			at org.jcodec.containers.mp4.boxes.Box.parseBox(Box.java:114) 
			at org.jcodec.containers.mp4.boxes.NodeBox.parseChildBox(NodeBox.java:62) 
			at org.jcodec.containers.mp4.boxes.NodeBox.parse(NodeBox.java:47) 
			at org.jcodec.containers.mp4.BoxUtil.parseBox(BoxUtil.java:16) 
			at org.jcodec.containers.mp4.MP4Util$Atom.parseBox(MP4Util.java:148) 
			at org.jcodec.containers.mp4.MP4Util.parseMovieChannel(MP4Util.java:65) 
			at org.jcodec.containers.mp4.demuxer.MP4Demuxer.findMovieBox(MP4Demuxer.java:54) 
			at org.jcodec.containers.mp4.demuxer.MP4Demuxer.<init>(MP4Demuxer.java:46) 
			at org.jcodec.api.FrameGrab8Bit.createFrameGrab8Bit(FrameGrab8Bit.java:52) 
			at org.jcodec.api.android.AndroidFrameGrab8Bit.createAndroidFrameGrab8Bit(AndroidFrameGrab8Bit.java:42) 
			at com.example.viet.myappdemo.VideoActivity.getFrame(VideoActivity.java:280) 
			at com.example.viet.myappdemo.VideoActivity.access$100(VideoActivity.java:45) 
			at com.example.viet.myappdemo.VideoActivity$2.run(VideoActivity.java:247) 
			at android.os.Handler.handleCallback(Handler.java:739) 
			at android.os.Handler.dispatchMessage(Handler.java:95) 
			at android.os.Looper.loop(Looper.java:148) 
			at android.app.ActivityThread.main(ActivityThread.java:5417) 
			at java.lang.reflect.Method.invoke(Native Method) 
			at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
			at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
```

I've modified my code as below:

```java
FileChannelWrapper ch = null;
        try {
            File file = new File(mVideoPath);
            AndroidFrameGrab8Bit fg = AndroidFrameGrab8Bit.createAndroidFrameGrab8Bit(NIOUtils.readableChannel(file));

            fg.seekToFramePrecise((int)(currentPosition*30/1000)); //get frame from a 30fps clip
            Bitmap bitmap = fg.getFrame();
            return bitmap;
        }catch (IOException ex) {
            ex.printStackTrace();
        } catch (JCodecException ex) {
            ex.printStackTrace();
        }  finally {
            NIOUtils.closeQuietly(ch);
        }
```

In addition, frame grabbing on high res video is significantly longer with version 0.2.0 than 0.1.9 (about 2 min).

**Comment by svitvitskiy** [comment]
Could you post a video on which it crashes now?

**Comment by vxhviet** [comment]
Still the same video, this one [dropbox](https://www.dropbox.com/s/nolffy73aj4rvvi/documentariesandyou.mp4?dl=0)
Do you think my code look fine? If I recall correctly, `AndroidFrameGrab8Bit.createAndroidFrameGrab8Bit` doesnt really return a `AndroidFrameGrab8Bit` (sorry I'm on my phone  so I can't really check this).
Thank you for your time.
