### ISSUE TITLE
Exception on every mp4 made by a samsung J3 - 6

### ISSUE THREAD

**Issue by aramponi** [jcodec/jcodec#136]
the file can be found here https://storage.googleapis.com/pubic/20160603_163316.mp4

Exception in thread "main" java.lang.RuntimeException: Invalid code prefix 0000000000000000
	at org.jcodec.common.io.VLC.readVLC(VLC.java:118)
	at org.jcodec.common.io.VLCBuilder$1.readVLC(VLCBuilder.java:57)
	at org.jcodec.codecs.h264.io.CAVLC.readCoeffs(CAVLC.java:201)
	at org.jcodec.codecs.h264.io.CAVLC.readACBlock(CAVLC.java:324)
	at org.jcodec.codecs.h264.decode.SliceReader.readResidualAC(SliceReader.java:319)
	at org.jcodec.codecs.h264.decode.SliceReader.readLuma(SliceReader.java:886)
	at org.jcodec.codecs.h264.decode.SliceReader.readResidualLuma(SliceReader.java:865)
	at org.jcodec.codecs.h264.decode.SliceReader.readIntraNxN(SliceReader.java:857)
	at org.jcodec.codecs.h264.decode.SliceReader.readMBlockIInt(SliceReader.java:1017)
	at org.jcodec.codecs.h264.decode.SliceReader.readMBlockI(SliceReader.java:1011)
	at org.jcodec.codecs.h264.decode.SliceReader.readMBlock(SliceReader.java:994)
	at org.jcodec.codecs.h264.decode.SliceReader.readMacroblock(SliceReader.java:159)
	at org.jcodec.codecs.h264.decode.SliceDecoder.decodeMacroblocks(SliceDecoder.java:99)
	at org.jcodec.codecs.h264.decode.SliceDecoder.decodeFromReader(SliceDecoder.java:73)
	at org.jcodec.codecs.h264.H264Decoder$FrameDecoder.decodeFrame(H264Decoder.java:158)
	at org.jcodec.codecs.h264.H264Decoder.decodeFrame8BitFromNals(H264Decoder.java:103)
	at org.jcodec.codecs.h264.H264Decoder.decodeFrame8Bit(H264Decoder.java:99)
	at org.jcodec.api.specific.AVCMP4Adaptor.decodeFrame8Bit(AVCMP4Adaptor.java:82)
	at org.jcodec.api.FrameGrab8Bit.getNativeFrame(FrameGrab8Bit.java:240)

**Comment by zhuker** [comment]
reproduced in https://github.com/jcodec/jcodec/pull/217
