### ISSUE TITLE
ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by simonkramer** [jcodec/jcodec#145]
Executing

transform.transform(pic, toEncode);

in

public void encodeNativeFrame(Picture pic)

can throw the following exception:

java.lang.ArrayIndexOutOfBoundsException: 574860
	at org.jcodec.scale.RgbToYuv420j.transform(RgbToYuv420j.java:31)

Please, how can we fix this?

**Comment by evilkirin** [comment]
I guess you and I hit the same wall when trying to grab some frames and encode them back to a mp4 file.

It may be because the encoding of the pic you supplied is `Yuv420j` rather than the source color space of the transformer which is `Rgb`, and the planes or the structure of how they layout the samples are totally different. When you walk up the calling methods, you can find this method in `AVCMP4Adapter`:

```java
@Override
    public Picture8Bit decodeFrame8Bit(Packet packet, byte[][] data) {
        updateState(packet);

        Picture8Bit pic = decoder.decodeFrame8Bit(packet.getData(), data);
        Rational pasp = meta.getPixelAspectRatio();

        if (pasp != null) {
            // TODO: transform
        }

        return pic;
    }
```

You see, the transformation is yet to be done, and so the color space of the picture you get when trying to get the next native frame is never changed, and yes it's `Yuv420j`. But to my surprise, when you throw the frame back to the `SequenceEncoder8Bit.encodeNativeFrame`, the reverse transformation from `Rgb` to `Yuv420j` just sit there and can't wait to blow your mind.

Although I don't know what's the most appropriate way to do this, just a noob really, I come up with a kinda working version:

```
```

**Comment by rsri** [comment]
Any fix for this problem? I've encountered the same problem.

**Comment by rsri** [comment]
Crash log:

java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
09-16 22:10:29.913 17948-29037/com.pic2fro.pic2fro W/System.err:     at org.jcodec.common.model.Picture8Bit.getPlaneData(Picture8Bit.java:97)
09-16 22:10:29.914 17948-29037/com.pic2fro.pic2fro W/System.err:     at org.jcodec.codecs.h264.encode.MBEncoderI16x16.predictChroma(MBEncoderI16x16.java:202)
09-16 22:10:29.914 17948-29037/com.pic2fro.pic2fro W/System.err:     at org.jcodec.codecs.h264.encode.MBEncoderI16x16.chroma(MBEncoderI16x16.java:66)
09-16 22:10:29.914 17948-29037/com.pic2fro.pic2fro W/System.err:     at org.jcodec.codecs.h264.encode.MBEncoderI16x16.encodeMacroblock(MBEncoderI16x16.java:49)
09-16 22:10:29.914 17948-29037/com.pic2fro.pic2fro W/System.err:     at org.jcodec.codecs.h264.H264Encoder.encodeMacroblock(H264Encoder.java:294)
09-16 22:10:29.914 17948-29037/com.pic2fro.pic2fro W/System.err:     at org.jcodec.codecs.h264.H264Encoder.encodeSlice(H264Encoder.java:275)
09-16 22:10:29.914 17948-29037/com.pic2fro.pic2fro W/System.err:     at org.jcodec.codecs.h264.H264Encoder.doEncodeFrame8Bit(H264Encoder.java:166)
09-16 22:10:29.914 17948-29037/com.pic2fro.pic2fro W/System.err:     at org.jcodec.codecs.h264.H264Encoder.encodeFrame8Bit(H264Encoder.java:103)
09-16 22:10:29.914 17948-29037/com.pic2fro.pic2fro W/System.err:     at com.example.test..SequenceEncoder$override.encodeFrame(SequenceEncoder.java:82)

SequenceEncoder is just a wee-bit modified implementation of SequenceEncoder8bit class.
