### ISSUE TITLE
Getting ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by CBribiescas** [jcodec/jcodec#148]
I'm using version 0.1.9 and having issues grabbing frame data.  Here is my code:

`package tempt;
/*
 * To extract frames from a mp4(avc) video
 *
 */
import org.jcodec.api.JCodecException;
import org.jcodec.api.awt.FrameGrab;
import org.jcodec.common.FileChannelWrapper;
import org.jcodec.common.NIOUtils;

import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
//import org.jcodec.common.io.FileChannelWrapper;

public class Main {

    static String in = "/data/ml/input/test.mp4";
    static String out = "/data/ml/output/out.jpg";
    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) throws IOException, JCodecException {
            st();
        }

    public static void st() throws IOException, JCodecException {
        BufferedImage frame = getFrame(new File(in), 1);
        ImageIO.write(frame, "jpg", new File(out));
    }

    public static BufferedImage getFrame(File file, double sec) throws JCodecException , IOException {
        FileChannelWrapper ch = null;
        try {
            ch = NIOUtils.readableFileChannel(file);
            return ((FrameGrab) new FrameGrab(ch).seekToSecondPrecise(sec)).getFrame();
        } finally {
            NIOUtils.closeQuietly(ch);
        }
    }
}`

The mp4 file I'm playing plays fine with vlc.  Not sure whats going on...  At runtime I get 
`Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 1
	at org.jcodec.codecs.h264.decode.SliceDecoder.reorder(SliceDecoder.java:400)
	at org.jcodec.codecs.h264.decode.SliceDecoder.buildRefListP(SliceDecoder.java:303)
	at org.jcodec.codecs.h264.decode.SliceDecoder.decode(SliceDecoder.java:205)
	at org.jcodec.codecs.h264.H264Decoder$FrameDecoder.decodeFrame(H264Decoder.java:87)
	at org.jcodec.codecs.h264.H264Decoder.decodeFrame(H264Decoder.java:61)
	at org.jcodec.api.specific.AVCMP4Adaptor.decodeFrame(AVCMP4Adaptor.java:71)
	at org.jcodec.api.FrameGrab.decodeLeadingFrames(FrameGrab.java:195)
	at org.jcodec.api.FrameGrab.seekToSecondPrecise(FrameGrab.java:116)
	at tempt.Main.getFrame(Main.java:38)
	at tempt.Main.st(Main.java:30)
	at tempt.Main.main(Main.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
`

Am I using this wrong, or is this another issue?

**Comment by opg7371** [comment]
@CBribiescas  Is it Solved?
