### ISSUE TITLE
Out of memory Error during encoding images to mp4

### ISSUE THREAD

**Issue by aomundada** [jcodec/jcodec#150]
I am trying to encode images to mp4. Following is my implementation. (I am using the [0.2.0 version](https://mvnrepository.com/artifact/org.jcodec/jcodec/0.2.0_1) of the library) :

`        AndroidSequenceEncoder8Bit se = AndroidSequenceEncoder8Bit.
                createSequenceEncoder8Bit(out, 15);

        for (int i = 0; i < images.size(); i++) {
            Bitmap bitmap = BitmapFactory.decodeFile(images.get(i));

            if(bitmap != null) {
                Log.e(TAG, "AndroidSequenceEncoder: " + i);
                se.encodeImage(bitmap);
            }
        }

        try {
            se.finish();
        } catch (IOException e){
            Log.e(TAG, "AndroidSequenceEncoder: encoder's Finish not worked");
        } finally {
            Toast.makeText(getActivity(), "GIF-Movie Created: " + out.getAbsolutePath(), Toast.LENGTH_SHORT).show();
        }
`

Is the implementation correct? 
Logcat: 

`10-17 13:49:11.019 24912-24912/com.sharecam.indepth E/dalvikvm-heap: Out of memory on a 12582928-byte allocation.
10-17 13:49:11.024 24912-24912/com.sharecam.indepth E/AndroidRuntime: FATAL EXCEPTION: main
                                                                      java.lang.OutOfMemoryError
                                                                          at org.jcodec.scale.BitmapUtil.getBuffer(BitmapUtil.java:165)
                                                                          at org.jcodec.scale.BitmapUtil.fromBitmap8BitImpl(BitmapUtil.java:103)
                                                                          at org.jcodec.scale.BitmapUtil.fromBitmap8BitImpl(BitmapUtil.java:80)
                                                                          at org.jcodec.scale.BitmapUtil.fromBitmap8Bit(BitmapUtil.java:37)
                                                                          at org.jcodec.api.android.AndroidSequenceEncoder8Bit.encodeImage(AndroidSequenceEncoder8Bit.java:48)`

The error seems to be coming due to this particular line : 165th line in [BitmapUtil.java  ](https://github.com/jcodec/jcodec/blob/master/android/src/main/org/jcodec/scale/BitmapUtil.java#L165)  @jcodec

**Comment by aomundada** [comment]
i solved it by downscaling my bitmap

`options.inSampleSize = wdth/320`
