### ISSUE TITLE
WebP image decoding seems to be broken

### ISSUE THREAD

**Issue by barneypitt** [jcodec/jcodec#157]
It's possible I'm using the code wrongly, I can't find any code examples which do this, so I'm winging it. I have the following code:

    public static void main(String... ignored) throws IOException, JCodecException
    {
        VP8Decoder decoder = new VP8Decoder();
        System.out.println("in " + new File(".").getCanonicalPath());
        File file = new File(".\\lib\\BrickWall.webp");
        file = file.getCanonicalFile();
        System.out.println("decoding " + file);
        try (FileInputStream in = new FileInputStream(file))
        {
            byte[] bytes = readBytesFully(in);
            ByteBuffer buffer = ByteBuffer.wrap(bytes);
            decoder.decode(buffer);
        }
        Picture picture = decoder.getPicture();
        BufferedImage image = AWTUtil.toBufferedImage(picture);

        // Doesn't work:
        //BufferedImage image = FrameGrab.getFrame(file, 0);

        JFrame frame = new JFrame("vp8.TestDecode");
        frame.getContentPane().add(new JLabel(new ImageIcon(image)));
        frame.pack();
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
    }

    public static byte[] readBytesFully(InputStream in)
    {
        try
        {
            ByteArrayOutputStream out=new ByteArrayOutputStream();
            BufferedInputStream bufferedIn=new BufferedInputStream(in);
            drain(bufferedIn, out);
            out.flush();
            return out.toByteArray();
        }
        catch (Exception e)
        {
            throw new RuntimeException(e);
        }
    }

    public static void drain(InputStream inputStream, OutputStream outputStream)
    {
        try
        {
            byte[] buf=new byte[1024];
            int count;
            while ((count=inputStream.read(buf)) != -1)
            {
                outputStream.write(buf, 0, count);
            }
        }
        catch (IOException e)
        {
            throw new RuntimeException(e);
        }
    }

where the file is downloaded from http://www.gstatic.com/webp/gallery/1.webp (same error on other webp images from other sources), but this crashes out with the following assertion, in decoder.decode():

Exception in thread "main" java.lang.AssertionError
    at org.jcodec.common.Assert.assertEquals(Assert.java:22)
    at org.jcodec.codecs.vp8.VP8Decoder.decode(VP8Decoder.java:73)
    at vp8.TestDecode.main(TestDecode.java:29)

which originates here in VP8Decoder.java:

    int loopFilterDeltaFlag = headerDecoder.decodeBit();
    Assert.assertEquals(1, loopFilterDeltaFlag);

**Comment by svitvitskiy** [comment]
I'll have a look, thanks

Stan

**Comment by barneypitt** [comment]
Don't suppose you got a chance to look at this?

**Comment by svitvitskiy** [comment]
I am actually looking at this but has not made much progress yet.

**Comment by svitvitskiy** [comment]
WebP lossy should be supported now.
Sample code:
`
Transcoder transcoder = new Transcoder("image.webp", "image.png", Format.WEBP, Format.IMG, Codec.VP8, Codec.PNG, null, null, false, false, new ArrayList<Filter>());
transcoder.transcode();
`
Let me know if you just wanted to grab the frame to use it in Java.

**Comment by barneypitt** [comment]
Yes, I just want to grab the frame to use it in Java.

Thanks!

**Comment by barneypitt** [comment]
PS, I would like to use the image for display purposes in both Android 
and AWT, if that helps.

Thanks

**Comment by CrackerKSR** [comment]
Can we extract each frame of animated webp. (then I would resize each bitmap frames)
After that Encode those bitmaps(resized) into animated webp ?
