### ISSUE TITLE
converted file .ts in .mp4 not play on exoplayer

### ISSUE THREAD

**Issue by Kyba1985** [jcodec/jcodec#159]
Hi, 
i used this library to create mp4 file from ts in android project. The file was created with copy copy in audio and video format. The extracted file was not able to be played in exoplayer2. The native player and vlc can play the file. In exoplayer i had this printstacktrace:

### E/LoadTask: Unexpected exception loading stream
                                                                             java.lang.IllegalArgumentException: childAtomSize should be positive
                                                                                 at com.google.android.exoplayer2.util.Assertions.checkArgument(Assertions.java:51)
                                                                                 at com.google.android.exoplayer2.extractor.mp4.AtomParsers.parseAudioSampleEntry(AtomParsers.java:848)
                                                                                 at com.google.android.exoplayer2.extractor.mp4.AtomParsers.parseStsd(AtomParsers.java:608)
                                                                                 at com.google.android.exoplayer2.extractor.mp4.AtomParsers.parseTrak(AtomParsers.java:89)
                                                                                 at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.processMoovAtom(Mp4Extractor.java:334)
                                                                                 at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.processAtomEnded(Mp4Extractor.java:277)
                                                                                 at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.readAtomPayload(Mp4Extractor.java:268)
                                                                                 at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.read(Mp4Extractor.java:148)
                                                                                 at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:630)
                                                                                 at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
                                                                                 at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                                                                                 at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                                 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                                 at java.lang.Thread.run(Thread.java:833)

Do you have any idea about this type of error?

Thanks in advance.

**Comment by svitvitskiy** [comment]
Can you give me the file as well?

Stan

**Comment by Kyba1985** [comment]
Hi Stan, sure i send the file. Another clue for you the quicktime player not play the audio of the file, vlc and other android players yes.

At the moment the only way that i can use to transform .ts in .mp4 playable in exoplayer and the all other player is:

1- use Extractor provided from android api to demux audio e video track
2- save the two tracks in 2 files, .h264 and .aac
3- use mp4parser library to mux the tracks in new mp4.

I'm new to the context of media, mux, demux. 
One strange thing (for me) when create the mp4 file in correct way is when i read the audio track from extractor i must use this line (see ///////////): 

try {

                FileChannel out = new FileOutputStream(audio).getChannel();

                boolean sawEOS2 = false;
                int frameCount2 = 0;
                while (!sawEOS2) {
                    frameCount2++;

                    try {

                        audioBufferInfo.offset = offset;
                        audioBufferInfo.size = audioExtractor.readSampleData(audioBuf, offset);
/////////this line is request to work /////////
                        if (audioExtractor.getSampleFlags() == MediaCodec.BUFFER_FLAG_KEY_FRAME) {
//////////////////////////////////////////////////////
                            out.write(audioBuf);
                            audioBuf.clear();
                        }
                    } catch (Exception e) {
                        Log.e(TAG, e.getMessage());
                    }

                    if (videoBufferInfo.size < 0 || audioBufferInfo.size < 0) {
                        Log.d(TAG, "saw input EOS.");
                        sawEOS2 = true;
                        audioBufferInfo.size = 0;
                    } else {
                        audioBufferInfo.presentationTimeUs = audioExtractor.getSampleTime();
                        audioBufferInfo.flags = audioExtractor.getSampleFlags();
                        //muxer.writeSampleData(audioTrack, audioBuf, audioBufferInfo);
                        audioExtractor.advance();
                    }
                }

[segment1_0_av_export.mp4.zip](https://github.com/jcodec/jcodec/files/716098/segment1_0_av_export.mp4.zip)

                out.close();
                audioExtractor.release();
                audioExtractor = null;

            } catch (Exception ex) {
                ex.printStackTrace();
                Log.d(TAG, ex.getMessage());
            }

This line was not present in all example that i found. If you know why whit this line the file is correct for exoplayer and want to explain , i will appreciate. 

Thanks in advance.

**Comment by svitvitskiy** [comment]
Ok, you can now use org.jcodec.samples.transcode.Transcoder class to export M2TS into MP4. It will basically copy all your h.264 and AVC frames over and you won't have to create a temporary file.

`
Transcoder transcoder = new Transcoder(inFile, outFile, inputFormat, outputFormat, inputCodecVideo, outputCodecVideo, inputCodecAudio, outputCodecAudio, videoCopy, audioCopy, filters);
transcoder.transcode(); 
`
 
The only problem for now is that this class lives in Jcodec Samples maven project ('samples' subfolder) so you'll have to manually copy this class over to your project. This is due to PNG decoder and decoder that relies on JavaSE native implementation. I will port this class to JCodec main project soon.

**Comment by Kyba1985** [comment]
Ok thanks, i Will give It a try.
Another common issue that i found is the conversion time. With ffmpeg
convert TS to mp4 is fast, with jcodec or mp4parser + mediaextractor is
slow.

Forse example on s3 neo for a conversion jcodec used 12 seconds , ffmpeg
1.5 seconds.

Il 25 gen 2017 8:52 AM, "svitvitskiy" <notifications@github.com> ha scritto:

**Comment by svitvitskiy** [comment]
It depends what you refer to by 'conversion'. If it's just simple copying of encoded data (specified by 'videoCopy' and 'audioCopy' parameters) then it would be fast.

However if we are talking about the actual transcode it will be very slow with JCodec since it's implemented in pure java and java is very slow on Android (usually, especially on older phones).

**Comment by SKras** [comment]
I am wondering if org.jcodec.samples.transcode.Transcoder is already available in JCodec 0.1.9 or how to create MP4 files based on TS files?

I can't find a matching example on [github](https://github.com/jcodec/jcodec/tree/master/samples).
Is someone able to support here?

What I am trying to do is to create a MP4 stream on the fly while reading a TS stream.
The TS is free of any encryption and contains audio and video. The MP4 (ISOBMFF) has to contain audio and video as well and has to be encrypted with CENC (Common Encryption) where I have the AES-128 key.

So far I am able to demux the TS stream:

	public static void inspect(SeekableByteChannel aByteChannel) throws IOException {

		Set<Integer> programs = MTSDemuxer.getPrograms(aByteChannel);
		for (int program : programs) {
			System.out.println("Transcoding program " + "0x" + String.format("%x", program));
			aByteChannel.position(0);
			MTSDemuxer mts = new MTSDemuxer(aByteChannel, program);

			for (MPEGDemuxer.MPEGDemuxerTrack track : mts.getTracks()) {
				DemuxerTrackMeta theMetaData = track.getMeta();

				ByteBuffer bb = ByteBuffer.allocate(500 << 10);
				Packet packet = track.nextFrame(bb);
				ByteBuffer data = packet.getData();
				VideoDecoder vd = JCodecUtil.detectDecoder(data);

				System.out.println(theMetaData.getType().name() + " track detected in program 0x" + String.format("%x", program) + ".");
				System.out.println("detected decoder: " + vd);
				System.out.println();
			}
		}
	}

How can I put A/V into a ISOBMPP container and encrypt it with CENC?

**Comment by svitvitskiy** [comment]
I didn't upload jcodec-samples artifact to maven, so you won't find it in 0.1.9 . In version 0.2.0 however the transcoder is in the main jar, specifically org.jcodec.api.Transcoder. You should be able to convert TS to MP4 with no encription (you are welcome to submit patches). You will need to specify audio codec 'copy' and video codec 'copy', otherwise jcodec may attempt to transcode your video. Please use the org.jcodec.api.TranscodeMain as a guide to the transcoder API. I should be able to upload the 0.2.0 version to maven as soon as I have a couple of bugs fixed.
