### ISSUE TITLE
Adding audio to existing video (without losing video content)

### ISSUE THREAD

**Issue by TimbresDev** [jcodec/jcodec#187]
Thanks very much for 4d83bb0 (see #164) ! With this change, how can the transcoder  be used to add WAV to an **existing** movie - without losing the video content of that existing movie ?

If I run "TranscodeMain --o:ac=copy sound-to-add-to-silent-movie.wav existing-silent-movie.mp4" then the existing-silent-movie.mp4 loses the visuals. I get a mp4 that has sound but no image anymore. 

Put differently, can the transcoder be used to **merge** existing audio from a WAV file and existing video from a MP4 file to a new file ? If so, how ? Or is there another way to use jcodec to achieve this ?

**Comment by zhuker** [comment]
technically you are not allowed to add uncompressed audio (wav) to an MP4 file
are you sure you want it uncompressed?

**Comment by Baggerstapler** [comment]
Now that the Flags for the Transcoder have changed, whats the substitute for "--o:ac" ?

**Comment by svitvitskiy** [comment]
It's '-acodec'

**Comment by dodles** [comment]
Can someone tell me the command to do this now, I can't seem to get this to work. Thank you.

**Comment by tf0054** [comment]
Im using clojure but it can be done like this with jcode(0.2.3)
```
(let [^Source src-audio (SourceImpl. wav-filename Format/WAV
                                           (JcodecStub/Tuple_3 0 0 nil)
                                           (JcodecStub/selectSuitableTrack wav-filename Format/WAV TrackType/AUDIO))
            ^Source src-video (SourceImpl. file-video Format/MOV
                                           (JcodecStub/selectSuitableTrack file-video Format/MOV TrackType/VIDEO)
                                           (JcodecStub/Tuple_3 0 0 nil))]
        (timbre/debug "Start preparation." file-audio wav-filename file-video (.getAudioCodecMeta src-audio))
        (let [builder (Transcoder/newTranscoder)
              ^Sink sink (SinkImpl. transcoded-filename Format/MOV Codec/H264 Codec/PCM)]

          (.addSource builder src-audio)
          ;(.setSeekFrames builder 0 )
          ;builder.setSeekFrames(sources.size() - 1, cmd.getIntegerFlagID(index, FLAG_SEEK_FRAMES, 0)).setMaxFrames(sources.size() - 1, cmd.getIntegerFlagID(index, FLAG_MAX_FRAMES, 2147483647));
          (.addSource builder src-video)

          (.addSink builder sink)
          (.setAudioMapping builder 0 0 true)
          (.setVideoMapping builder 1 0 true)

          (timbre/debug "Start transcoder.")
          (let [^Transcoder transcoder (.create builder)]
            (.transcode transcoder))
          ))
```
One thing we have to think about is the wav should be encoded with samping rate = 25600 something which is according with fps of video. (25*1024=25600)

**Comment by dbu9** [comment]
I'm trying to incorporate wav into mp4, on version 0.2.5:

```
java -cp jcodec-0.2.5.jar:jcodec-javase-0.2.3.jar org.jcodec.api.transcode.TranscodeMain -i rec.wav -i 1.mp4 out.mp4
No frames output.
Exception in thread "main" java.lang.RuntimeException: Only PCM audio encoding (RAW audio) is supported.
	at org.jcodec.api.transcode.SinkImpl.createAudioEncoder(SinkImpl.java:169)
	at org.jcodec.api.transcode.SinkImpl.encodeAudio(SinkImpl.java:184)
	at org.jcodec.api.transcode.SinkImpl.outputAudioFrame(SinkImpl.java:222)
	at org.jcodec.api.transcode.Transcoder$Stream.finalFlushQueues(Transcoder.java:209)
	at org.jcodec.api.transcode.Transcoder.transcode(Transcoder.java:404)
	at org.jcodec.api.transcode.TranscodeMain.main(TranscodeMain.java:367)
```

That's an erro I get. Any suggestion?.
