### ISSUE TITLE
H264 decoding failed

### ISSUE THREAD

**Issue by mohzhang** [jcodec/jcodec#26]
[java] java.lang.NullPointerException
     [java]     at org.jcodec.codecs.h264.decode.deblock.DeblockingFilter.calcBsH(DeblockingFilter.java:167)
     [java]     at org.jcodec.codecs.h264.decode.deblock.DeblockingFilter.deblockFrame(DeblockingFilter.java:80)
     [java]     at org.jcodec.codecs.h264.H264Decoder$FrameDecoder.decodeFrame(H264Decoder.java:101)
     [java]     at org.jcodec.codecs.h264.H264Decoder.decodeFrame(H264Decoder.java:61)
     [java]     at org.jcodec.api.specific.AVCMP4Adaptor.decodeFrame(AVCMP4Adaptor.java:40)
     [java]     at org.jcodec.api.FrameGrab.decodeLeadingFrames(FrameGrab.java:184)
     [java]     at org.jcodec.api.FrameGrab.seekToSecondPrecise(FrameGrab.java:91)

Test case:
http://downloads.dvdloc8.com/trailers/divxdigest/fantastic_four_rise_of_the_silver_surfer-trailer.zip

**Comment by svitvitskiy** [comment]
I think this file has been fixed already. Please try some of the later releases.

Assigning it to myself to take care of the testcases.
