### ISSUE TITLE
MXFDemuxer IllegalArgumentException

### ISSUE THREAD

**Issue by zhuker** [jcodec/jcodec#282]
MXFDemuxer throws IllegalArgumentException in constructor

```java
File mxf = new File("LTD16562_SYN16562-PUNCH.mxf");
MXFDemuxer demuxer = new MXFDemuxer(NIOUtils.readableChannel(mxf));
```

**Comment by svitvitskiy** [comment]
@zhuker do you think it's fixed already?

**Comment by zhuker** [comment]
@svitvitskiy have to test

**Comment by zhuker** [comment]
@svitvitskiy `MXFDemuxerTest.testOpenAvidMxf` fails with
```
java.lang.ArrayIndexOutOfBoundsException: 0
	at org.jcodec.containers.mxf.MXFDemuxer$MXFDemuxerTrack.nextFrame(MXFDemuxer.java:380)
	at org.jcodec.containers.mxf.MXFDemuxerTest.testOpenAvidMxf(MXFDemuxerTest.java:22)
```
