### ISSUE TITLE
java.lang.IllegalArgumentException 	at java.nio.Buffer.limit(Buffer.java:275)

### ISSUE THREAD

**Issue by smaznet** [jcodec/jcodec#302]
My code: 
``` java
File wavFile = new File( "song.wav" );
audioDemuxer = JCodecUtil.createDemuxer( Format.WAV, wavFile );
```

Error: 
``` java
java.lang.IllegalArgumentException
	at java.nio.Buffer.limit(Buffer.java:275)
	at org.jcodec.common.io.NIOUtils.read(NIOUtils.java:69)
	at org.jcodec.common.io.NIOUtils.readString(NIOUtils.java:228)
	at org.jcodec.codecs.wav.WavHeader.readChannel(WavHeader.java:240)
	at org.jcodec.codecs.wav.WavDemuxer.<init>(WavDemuxer.java:43)
	at org.jcodec.common.JCodecUtil.createDemuxer(JCodecUtil.java:220)
	at ExampleApplet.setup(ExampleApplet.java:117)
```

please help me

**Comment by AkashShalu** [comment]
try working with mp4 format.

**Comment by svitvitskiy** [comment]
Could you please upload your file so I can have a look?

**Comment by AkashShalu** [comment]
Sir
        Good Afternoon, Your Library is awesome. it works fine on redmi 4,
Samsung J7.  but when i am using Lenovo vibe (Marashmellow).
  itakes lot of time and very slow, about 2 minutes for 20 bitmaps. please
tell me a sweet solution asap. am wating.

Thank You Very much.

your library is very impressive its works on mi4 0
