### ISSUE TITLE
Unsupported h264 feature: scaling list.

### ISSUE THREAD

**Issue by ddalcu** [jcodec/jcodec#309]
Exception in thread "main" java.lang.RuntimeException: Unsupported h264 feature: scaling list.
	at org.jcodec.codecs.h264.H264Decoder$FrameDecoder.validateSupportedFeatures(H264Decoder.java:222)
	at org.jcodec.codecs.h264.H264Decoder$FrameDecoder.init(H264Decoder.java:190)
	at org.jcodec.codecs.h264.H264Decoder$FrameDecoder.decodeFrame(H264Decoder.java:139)
	at org.jcodec.codecs.h264.H264Decoder.decodeFrameFromNals(H264Decoder.java:103)
	at org.jcodec.codecs.h264.H264Decoder.decodeFrame(H264Decoder.java:99)
	at org.jcodec.api.specific.AVCMP4Adaptor.decodeFrame(AVCMP4Adaptor.java:68)
	at org.jcodec.api.FrameGrab.decodeLeadingFrames(FrameGrab.java:178)
	at org.jcodec.api.FrameGrab.seekToFramePrecise(FrameGrab.java:118)
	at org.jcodec.api.FrameGrab.getFrameFromFile(FrameGrab.java:291)
	at xphoto.gallery.VideoThumbnailer.main(VideoThumbnailer.java:20)

**Comment by svitvitskiy** [comment]
Dublicate of #198
