### ISSUE TITLE
JCodec AWTSequenceEncoder: 'Exception in thread "main" java.nio.BufferOverflowException' on resized images

### ISSUE THREAD

**Issue by neelchauhan** [jcodec/jcodec#325]
If I try to encode certain images resized via Graphics2D, I get an error like this:

    Exception in thread "main" java.nio.BufferOverflowException
    	at java.nio.Buffer.nextPutIndex(Buffer.java:521)
    	at java.nio.HeapByteBuffer.put(HeapByteBuffer.java:169)
    	at org.jcodec.codecs.h264.H264Utils.escapeNAL(H264Utils.java:164)
    	at org.jcodec.codecs.h264.H264Encoder.encodeSlice(H264Encoder.java:293)
    	at org.jcodec.codecs.h264.H264Encoder.doEncodeFrame(H264Encoder.java:170)
    	at org.jcodec.codecs.h264.H264Encoder.encodeFrame(H264Encoder.java:106)
    	at org.jcodec.api.transcode.SinkImpl.encodeVideo(SinkImpl.java:173)
    	at org.jcodec.api.transcode.SinkImpl.outputVideoFrame(SinkImpl.java:220)
    	at org.jcodec.api.SequenceEncoder.encodeNativeFrame(SequenceEncoder.java:101)
    	at org.jcodec.api.awt.AWTSequenceEncoder.encodeImage(AWTSequenceEncoder.java:49)
    	at umg.shadow.postprocessing.ImageSequenceToMP4.createMP4(ImageSequenceToMP4.java:112)
    	at umg.shadow.postprocessing.ImageSequenceToMP4.run(ImageSequenceToMP4.java:59)
    	at umg.shadow.cli.Main.main(Main.java:34)

This issue comes for certain images resized at certain resolutions. At other resolutions, the same image may not give an error, but another might. However, if I encode at the original resolution, I can encode all the images. Some other resolutions also work.

**Comment by svitvitskiy** [comment]
Hi, thanks for reporting. It would be helpful if you attached the example images or a code snippet to reproduce the problem. Thanks!
