### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException while parsing MKV

### ISSUE THREAD

**Issue by nickrobinson** [jcodec/jcodec#329]
I am attempting to process an MKV video using jcodec and am using the following code in order to do so. Every time I try to run it I get a ArrayIndexOutOfBoundsException due to org.jcodec.codecs.h264.decode.SliceDecoder.putMacroblock attempting an arraycopy. I have included a stacktrace as well as a dump of the last few MKV elements before the exception. Any tips on how I could debug this issue further on my end?

```
StreamingMkvReader mkvStreamReader = StreamingMkvReader.createDefault(new InputStreamParserByteSource(result.getPayload()));
            log.info("StreamingMkvReader created for stream {} ", streamName);
            try {
                while (mkvStreamReader.mightHaveNext()) {
                    Optional<MkvElement> mkvElementOptional = mkvStreamReader.nextIfAvailable();
                    if (mkvElementOptional.isPresent()) {
                        //Apply the MkvElement to the visitor
                        log.error(mkvElementOptional.get().toString());
                        mkvElementOptional.get().accept(elementVisitor);
                    }
                }
            } catch (MkvElementVisitException e) {
                log.error("Exception while accepting visitor {}", e);
            }
```

Stack Trace:
```
java.lang.ArrayIndexOutOfBoundsException
	at java.lang.System.arraycopy(Native Method)
	at org.jcodec.codecs.h264.decode.SliceDecoder.putMacroblock(SliceDecoder.java:198)
	at org.jcodec.codecs.h264.decode.SliceDecoder.decodeMacroblocks(SliceDecoder.java:104)
	at org.jcodec.codecs.h264.decode.SliceDecoder.decodeFromReader(SliceDecoder.java:73)
	at org.jcodec.codecs.h264.H264Decoder$FrameDecoder.decodeFrame(H264Decoder.java:152)
	at org.jcodec.codecs.h264.H264Decoder.decodeFrameFromNals(H264Decoder.java:103)
	at com.amazonaws.kinesisvideo.parser.examples.KinesisVideoRendererExample$ParsingVisitor.visit(KinesisVideoRendererExample.java:230)
	at com.amazonaws.kinesisvideo.parser.mkv.MkvDataElement.accept(MkvDataElement.java:138)
	at com.amazonaws.kinesisvideo.parser.mkv.visitors.CompositeMkvElementVisitor.visitAll(CompositeMkvElementVisitor.java:68)
	at com.amazonaws.kinesisvideo.parser.mkv.visitors.CompositeMkvElementVisitor.visit(CompositeMkvElementVisitor.java:57)
	at com.amazonaws.kinesisvideo.parser.mkv.MkvDataElement.accept(MkvDataElement.java:138)
	at com.amazonaws.kinesisvideo.parser.examples.GetMediaWorker.run(GetMediaWorker.java:94)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

Last few MKV elements before exception:
```
[ERROR] 2018-03-06 11:04:09.597 [pool-2-thread-1] GetMediaWorker - MkvEndMasterElement(super=MkvElement(elementMetaData=EBMLElementMetaData(typeInfo=EBMLTypeInfo(id=29555, name=Tag, level=2, type=MASTER, isRecursive=false), elementNumber=85), elementPath=[EBMLElementMetaData(typeInfo=EBMLTypeInfo(id=408125543, name=Segment, level=0, type=MASTER, isRecursive=false), elementNumber=8), EBMLElementMetaData(typeInfo=EBMLTypeInfo(id=307544935, name=Tags, level=1, type=MASTER, isRecursive=false), elementNumber=84)]))
[ERROR] 2018-03-06 11:04:09.597 [pool-2-thread-1] GetMediaWorker - MkvEndMasterElement(super=MkvElement(elementMetaData=EBMLElementMetaData(typeInfo=EBMLTypeInfo(id=307544935, name=Tags, level=1, type=MASTER, isRecursive=false), elementNumber=84), elementPath=[EBMLElementMetaData(typeInfo=EBMLTypeInfo(id=408125543, name=Segment, level=0, type=MASTER, isRecursive=false), elementNumber=8)]))
[ERROR] 2018-03-06 11:04:09.598 [pool-2-thread-1] GetMediaWorker - MkvStartMasterElement(super=MkvElement(elementMetaData=EBMLElementMetaData(typeInfo=EBMLTypeInfo(id=524531317, name=Cluster, level=1, type=MASTER, isRecursive=false), elementNumber=95), elementPath=[EBMLElementMetaData(typeInfo=EBMLTypeInfo(id=408125543, name=Segment, level=0, type=MASTER, isRecursive=false), elementNumber=8)]), dataSize=489453)
[ERROR] 2018-03-06 11:04:09.607 [pool-2-thread-1] GetMediaWorker - MkvDataElement(super=MkvElement(elementMetaData=EBMLElementMetaData(typeInfo=EBMLTypeInfo(id=191, name=CRC-32, level=-1, type=BINARY, isRecursive=false), elementNumber=96), elementPath=[EBMLElementMetaData(typeInfo=EBMLTypeInfo(id=408125543, name=Segment, level=0, type=MASTER, isRecursive=false), elementNumber=8), EBMLElementMetaData(typeInfo=EBMLTypeInfo(id=524531317, name=Cluster, level=1, type=MASTER, isRecursive=false), elementNumber=95)]), dataSize=4)
[ERROR] 2018-03-06 11:04:09.607 [pool-2-thread-1] GetMediaWorker - MkvDataElement(super=MkvElement(elementMetaData=EBMLElementMetaData(typeInfo=EBMLTypeInfo(id=231, name=Timecode, level=2, type=UINTEGER, isRecursive=false), elementNumber=97), elementPath=[EBMLElementMetaData(typeInfo=EBMLTypeInfo(id=408125543, name=Segment, level=0, type=MASTER, isRecursive=false), elementNumber=8), EBMLElementMetaData(typeInfo=EBMLTypeInfo(id=524531317, name=Cluster, level=1, type=MASTER, isRecursive=false), elementNumber=95)]), dataSize=2)
[ERROR] 2018-03-06 11:04:09.628 [pool-2-thread-1] GetMediaWorker - MkvDataElement(super=MkvElement(elementMetaData=EBMLElementMetaData(typeInfo=EBMLTypeInfo(id=163, name=SimpleBlock, level=2, type=BINARY, isRecursive=false), elementNumber=98), elementPath=[EBMLElementMetaData(typeInfo=EBMLTypeInfo(id=408125543, name=Segment, level=0, type=MASTER, isRecursive=false), elementNumber=8), EBMLElementMetaData(typeInfo=EBMLTypeInfo(id=524531317, name=Cluster, level=1, type=MASTER, isRecursive=false), elementNumber=95)]), dataSize=94598)
```

**Comment by zhuker** [comment]
can you provide the file it can be reproduced on?

**Comment by nickrobinson** [comment]
Here is a sample video that I am dealing with. I am using AWS Kinesis Video Streams in order to transmit a live stream from my camera. This results in a stream that is broken down into 2.5 second MKV fragments. The file below is the output that jcodec is receiving via my consumer library.

[video.mkv.zip](https://github.com/jcodec/jcodec/files/1793137/video.mkv.zip)

**Comment by mrrhysbutler** [comment]
Hi, experiencing the same issue, also with AWS KVS. Any updates on this one? Cheers.

**Comment by aaron-freshwater-aws** [comment]
We at KVS have merged Jonathan's changes into the parser library which provide a workaround to this still-open bug in JCodec.

**Comment by svitvitskiy** [comment]
Hey Aaron,

thanks for your comment, could you point me to the Jonathan's changes so that I could merge them in?

Thanks!
