### ISSUE TITLE
java.nio.BufferOverflowException

### ISSUE THREAD

**Issue by zhuanqizhirou** [jcodec/jcodec#342]
I have 200+ 600*600px bufferedImages, totally 40MB. While i =105, I got the java.nio.BufferOverflowException.

Code:
`SeekableByteChannel out = null;
        try {
            out = NIOUtils.writableFileChannel(path);
            AWTSequenceEncoder encoder = new AWTSequenceEncoder(out, Rational.R(24, 1));
            for (int i = 0; i < images.size(); i++) {
                System.out.println(i);
                BufferedImage image = images.get(i);
                encoder.encodeImage(image);
            }
            encoder.finish();
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            NIOUtils.closeQuietly(out);
        }`
Error:
`java.nio.BufferOverflowException
	at java.nio.Buffer.nextPutIndex(Buffer.java:521)
	at java.nio.HeapByteBuffer.put(HeapByteBuffer.java:169)
	at org.jcodec.codecs.h264.H264Utils.escapeNAL(H264Utils.java:218)
	at org.jcodec.codecs.h264.H264Encoder.encodeSlice(H264Encoder.java:309)
	at org.jcodec.codecs.h264.H264Encoder.doEncodeFrame(H264Encoder.java:184)
	at org.jcodec.codecs.h264.H264Encoder.encodeFrame(H264Encoder.java:117)
	at org.jcodec.api.transcode.SinkImpl.encodeVideo(SinkImpl.java:173)
	at org.jcodec.api.transcode.SinkImpl.outputVideoFrame(SinkImpl.java:220)
	at org.jcodec.api.SequenceEncoder.encodeNativeFrame(SequenceEncoder.java:101)
	at org.jcodec.api.awt.AWTSequenceEncoder.encodeImage(AWTSequenceEncoder.java:49)
	at com.yicomm.utils.templet.TempletOneBO.toMP4(TempletOneBO.java:645)
	at com.yicomm.utils.templet.TempletOneBO.stepAll(TempletOneBO.java:115)
	at com.yicomm.service.impl.MainVideoServiceImpl.createVideo(MainVideoServiceImpl.java:43)
	at com.yicomm.utils.templet.TempletOneBO.main(TempletOneBO.java:693)`

**Comment by Dacaspex** [comment]
I'm having the same issue. It seems that when the image width and height I can encode a few more images before I get a `BufferOverflowException`. I haven't been able to find out why this is the case.

p.s. Could you format your code (using code blocks) to make it easier to read?

**Comment by chrisheaththomas** [comment]
I also have the same issue at approximately 75MB.
