### ISSUE TITLE
ArrayIndexOutOfBoundsException when trying to get frame of video

### ISSUE THREAD

**Issue by amanchoudhary** [jcodec/jcodec#370]
Hi, I want to get a frame out of a video. This has worked well for all the videos apart from one with a high resolution video. Following are the details and stack trace of it
Dimensions: 1080 * 1920
Codecs: H.264, AAC

Stacktrace:
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/Users/aman.choudhary/Desktop/video.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: isommp42
    creation_time   : 2019-03-30 12:56:46
  Duration: 00:00:11.84, start: 0.000000, bitrate: 2089 kb/s
    Stream #0:0(eng): Video: h264 (Baseline) (avc1 / 0x31637661), yuv420p, 1920x1080, 1992 kb/s, SAR 1:1 DAR 16:9, 24.82 fps, 24.83 tbr, 90k tbn, 180k tbc (default)
    Metadata:
      rotate          : 270
      creation_time   : 2019-03-30 12:56:46
      handler_name    : VideoHandle
    Side data:
      displaymatrix: rotation of 90.00 degrees
    Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 95 kb/s (default)
    Metadata:
      creation_time   : 2019-03-30 12:56:46
      handler_name    : SoundHandle
11:08:09.761 [main] ERROR c.p.v.c.k.util.ImageExtractionUtils – Exception occured while trying to extract image from video
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.ArrayIndexOutOfBoundsException: 8160
	at org.jcodec.codecs.h264.H264Decoder$FrameDecoder.waitForSure(H264Decoder.java:169)
	at org.jcodec.codecs.h264.H264Decoder$FrameDecoder.decodeFrame(H264Decoder.java:147)
	at org.jcodec.codecs.h264.H264Decoder.decodeFrameFromNals(H264Decoder.java:103)
	at org.jcodec.codecs.h264.H264Decoder.decodeFrame(H264Decoder.java:99)
	at org.jcodec.api.specific.AVCMP4Adaptor.decodeFrame(AVCMP4Adaptor.java:68)
	at org.jcodec.api.FrameGrab.decodeLeadingFrames(FrameGrab.java:178)
	at org.jcodec.api.FrameGrab.seekToFramePrecise(FrameGrab.java:118)
	at org.jcodec.api.FrameGrab.getFrameFromFile(FrameGrab.java:291)

**Comment by zhuker** [comment]
@amanchoudhary please provide sample file
