### ISSUE TITLE
The muxer track has finished muxing while encoding video

### ISSUE THREAD

**Issue by nevernervous** [jcodec/jcodec#371]
When encoding the video using AndroidSequenceEncoder with the images, I get the error message `The muxer track has finished muxing` after about 120 secs.

W/System.err: java.lang.IllegalStateException: The muxer track has finished muxing
        at org.jcodec.common.Preconditions.checkState(Preconditions.java:441)
W/System.err:     at org.jcodec.containers.mp4.muxer.CodecMP4MuxerTrack.addFrameInternal(CodecMP4MuxerTrack.java:99)
        at org.jcodec.containers.mp4.muxer.MP4MuxerTrack.addFrame(MP4MuxerTrack.java:84)
        at org.jcodec.containers.mp4.muxer.CodecMP4MuxerTrack.addFrame(CodecMP4MuxerTrack.java:94)
        at org.jcodec.api.transcode.SinkImpl.outputVideoPacket(SinkImpl.java:71)
        at org.jcodec.api.transcode.SinkImpl.outputVideoFrame(SinkImpl.java:223)
W/System.err:     at org.jcodec.api.SequenceEncoder.encodeNativeFrame(SequenceEncoder.java:101)
        at org.jcodec.api.android.AndroidSequenceEncoder.encodeImage(AndroidSequenceEncoder.java:50)

**Comment by zhuker** [comment]
can you post code which exposes this issue here

**Comment by zhuker** [comment]
@nevernervous
