### ISSUE TITLE
Getting error java.lang.RuntimeException: long term

### ISSUE THREAD

**Issue by dhrumilsheth9** [jcodec/jcodec#379]
I am getting the error of long term 
full stack trace

ava.lang.RuntimeException: long term
at org.jcodec.codecs.h264.decode.RefListManager.reorder(RefListManager.java:156)
at org.jcodec.codecs.h264.decode.RefListManager.buildRefListP(RefListManager.java:79)
at org.jcodec.codecs.h264.decode.RefListManager.getRefList(RefListManager.java:42)
at org.jcodec.codecs.h264.decode.SliceDecoder.decodeFromReader(SliceDecoder.java:71)
at org.jcodec.codecs.h264.H264Decoder$FrameDecoder.decodeFrame(H264Decoder.java:152)
at org.jcodec.codecs.h264.H264Decoder.decodeFrameFromNals(H264Decoder.java:103)

private void reorder(Picture[] result, int list) {
        if (sh.refPicReordering[list] == null)
            return;

        int predict = sh.frame_num;
        int maxFrames = 1 << (sh.sps.log2_max_frame_num_minus4 + 4);

        for (int ind = 0; ind < sh.refPicReordering[list][0].length; ind++) {
            switch (sh.refPicReordering[list][0][ind]) {
            case 0:
                predict = wrap(predict - sh.refPicReordering[list][1][ind] - 1, maxFrames);
                break;
            case 1:
                predict = wrap(predict + sh.refPicReordering[list][1][ind] + 1, maxFrames);
                break;
            case 2:
                throw new RuntimeException("long term");
            }
            for (int i = numRef[list] - 1; i > ind; i--)
                result[i] = result[i - 1];
            result[ind] = sRefs[predict];
            for (int i = ind + 1, j = i; i < numRef[list] && result[i] != null; i++) {
                if (result[i] != sRefs[predict])
                    result[j++] = result[i];
            }
        }
    }
The above error occurs when I am using rtsp link. However, in video the code works fine. Any help would be helpful.

**Comment by dhrumilsheth9** [comment]
Is there any way I can disable LTR(Long term reference) from code?

**Comment by svitvitskiy** [comment]
Could you please attach a sample video so I could take a look?

**Comment by dhrumilsheth9** [comment]
> Should be fixed in [30eb428](https://github.com/jcodec/jcodec/commit/30eb428f71cfacb342969558b37cd29d462e2256), please reopen if you find a file that doesn't work, please attach a video file as well.

Hey, @svitvitskiy  thank you for replying. I am using jcodec library in AWS Kinesis Video Streaming(KVS). I don't have any video as I am using live streaming and I am using kinesis video parser library. Here is the link  https://github.com/aws/amazon-kinesis-video-streams-parser-library.
While running kinesis video parser library it throws jcodec error as mentioned above. Though I will check the latest commit and will let you know if the error is solved or not.

**Comment by mrgiba** [comment]
Hello, what is the plan to release a new version of the library having this fix ? Thanks

**Comment by svitvitskiy** [comment]
Thanks, I'll try to do it ASAP.

Stan

**Comment by mrgiba** [comment]
Thanks, any expected date for the new release ?
