### ISSUE TITLE
What does this exception mean? What height is this refferring to? Error message below code

### ISSUE THREAD

**Issue by NewbieEngineer001** [jcodec/jcodec#381]
This is the code I am using to convert from jpeg to mp4. And got following error message. Any direction is much appreciated

`package com.test.examples;

import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;

import javax.imageio.ImageIO;

import org.jcodec.api.awt.AWTSequenceEncoder;
import org.jcodec.common.io.NIOUtils;
import org.jcodec.common.io.SeekableByteChannel;
import org.jcodec.common.model.Rational;

public class SecondVideoMaker {

	public static void main(String[] args) throws IOException{
		SeekableByteChannel out = null;
	    try {
	        out = NIOUtils.writableFileChannel("D:\\temp\\Jpegs_samples\\output1.mp4");
	        // for Android use: AndroidSequenceEncoder
	        AWTSequenceEncoder encoder = new AWTSequenceEncoder(out, Rational.R(25, 1));
	        for (int i =1; i < 4; i++) {
	            // Generate the image, for Android use Bitmap
	            BufferedImage image = ImageIO.read(new File("D:\\temp\\Jpegs_samples\\" + i + ".jpg"));//input files named 1.jpg ... 3.jpg
	            // Encode the image
	            encoder.encodeImage(image);
	        }
	        // Finalize the encoding, i.e. clear the buffers, write the header, etc.
	        encoder.finish();
	    } finally {
	        NIOUtils.closeQuietly(out);
	    }

	}

}`

Error I am getting
Exception in thread "main" java.lang.IllegalArgumentException: Component 1 height should be a multiple of 2 for colorspace: YUV420J
	at org.jcodec.common.model.Picture.<init>(Picture.java:61)
	at org.jcodec.common.model.Picture.createCropped(Picture.java:94)
	at org.jcodec.common.model.Picture.create(Picture.java:75)
	at org.jcodec.api.transcode.PixelStoreImpl.getPicture(PixelStoreImpl.java:25)
	at org.jcodec.api.SequenceEncoder.encodeNativeFrame(SequenceEncoder.java:94)
	at org.jcodec.api.awt.AWTSequenceEncoder.encodeImage(AWTSequenceEncoder.java:49)
	at com.test.examples.SecondVideoMaker.main(SecondVideoMaker.java:26)

**Comment by NewbieEngineer001** [comment]
Resolution of image read should be multiples of 2s (even numbers for width and height)
