### ISSUE TITLE
NPE while grabbing frame from MP4 video

### ISSUE THREAD

**Issue by ChiranjibKarn** [jcodec/jcodec#383]
I am using the latest version 0.2.5 of both jcodec and jcodec-javase. Same issue is there in 0.2.3 as well.

While grabbing frame from a MP4 video, it throws Null Pointer Exception.
Following is the complete stacktrace:
_java.lang.RuntimeException: java.lang.NullPointerException
        at org.jcodec.containers.mp4.BoxUtil.as(BoxUtil.java:45)
        at org.jcodec.codecs.aac.AACUtils.getCodecPrivate(AACUtils.java:97)
        at org.jcodec.containers.mp4.demuxer.MP4DemuxerTrackMeta.getCodecPrivate(MP4DemuxerTrackMeta.java:111)
        at org.jcodec.containers.mp4.demuxer.CodecMP4DemuxerTrack.<init>(CodecMP4DemuxerTrack.java:38)
        at org.jcodec.containers.mp4.demuxer.MP4Demuxer.newTrack(MP4Demuxer.java:71)
        at org.jcodec.containers.mp4.demuxer.MP4Demuxer.fromTrakBox(MP4Demuxer.java:66)
        at org.jcodec.containers.mp4.demuxer.MP4Demuxer.processHeader(MP4Demuxer.java:98)
        at org.jcodec.containers.mp4.demuxer.MP4Demuxer.findMovieBox(MP4Demuxer.java:86)
        at org.jcodec.containers.mp4.demuxer.MP4Demuxer.<init>(MP4Demuxer.java:77)
        at org.jcodec.containers.mp4.demuxer.MP4Demuxer.createMP4Demuxer(MP4Demuxer.java:50)
        at org.jcodec.api.FrameGrab.createFrameGrab(FrameGrab.java:60)
        **at org.jcodec.api.FrameGrab$createFrameGrab.call(Unknown Source)**
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:128)_

It says Unknown Source even though the file is available and I can print its name.

Attached here is the very same mp4 file (archived in zip file), that causes issue.

[sample.zip](https://github.com/jcodec/jcodec/files/3500982/sample.zip)

**Comment by svitvitskiy** [comment]
Fixed in ac63d66

**Comment by ChiranjibKarn** [comment]
Thanks.
Seems Maven repository not been updated with this fix.
