### ISSUE TITLE
How to use TranscodeMain in version 0.2.3?

### ISSUE THREAD

**Issue by lixuexia** [jcodec/jcodec#394]
I copy and modify the class TranscodeMain to suit my request.
The test code is :public static void main(String[] args) throws Exception {
        TranscoderBuilder builder = Transcoder.newTranscoder();
        List<Source> sources = new ArrayList<Source>();
        List<_3<Integer, Integer, Codec>> inputCodecsVideo = new ArrayList<_3<Integer, Integer, Codec>>();
        List<_3<Integer, Integer, Codec>> inputCodecsAudio = new ArrayList<_3<Integer, Integer, Codec>>();
        String srcVideo = "D:/A.mp4";
        String srcAudio = "D:/A.mp3";
        Format inputVideoFormat = Format.MOV;
        _3<Integer, Integer, Codec> inputCodecVideo = selectSuitableTrack(srcVideo, inputVideoFormat, TrackType.VIDEO);
        inputCodecsVideo.add(inputCodecVideo);
        Source sourceVideo = new SourceImpl(srcVideo, inputVideoFormat, inputCodecVideo, inputCodecVideo);
        Integer downscale = 1;
        sourceVideo.setOption(Options.DOWNSCALE, downscale);
        sourceVideo.setOption(Options.PROFILE, "default");
        sourceVideo.setOption(Options.INTERLACED, false);
        sources.add(sourceVideo);
        builder.addSource(sourceVideo);
        Format inputAudioFormat = Format.MPEG_AUDIO;
        _3<Integer, Integer, Codec> inputCodecAudio = selectSuitableTrack(srcAudio, inputAudioFormat, TrackType.AUDIO);
        inputCodecsAudio.add(inputCodecAudio);
        Source sourceAudio = new SourceImpl(srcVideo, inputAudioFormat, inputCodecVideo, inputCodecAudio);
        sourceAudio.setOption(Options.PROFILE, "default");
        sourceAudio.setOption(Options.INTERLACED, false);
        sources.add(sourceAudio);
        builder.addSource(sourceAudio);
        builder.setSeekFrames(sources.size() - 1, 0).setMaxFrames(sources.size() - 1, Integer.MAX_VALUE);

        String output = "D:/B.WAV";
        List<Sink> sinks = new ArrayList<>();
        Format outputFormat = Format.MOV;//getFormatFromExtension("B.mp4");
        Codec outputCodecVideo = extensionToC.get("264");
        Codec outputCodecAudio = audioCodecsForF.get(outputFormat);

        int audioMap = 0;
        int videoMap = 0;

        Sink sink = new SinkImpl(output, outputFormat, outputCodecVideo, outputCodecAudio);
        sinks.add(sink);
        builder.addSink(sink);
        builder.setAudioMapping(audioMap, sinks.size() - 1, false);
        builder.setVideoMapping(videoMap, sinks.size() - 1, false);

        builder.addFilter(sinks.size() - 1, new DumpMvFilter(true));

        if (sources.isEmpty() || sinks.isEmpty()) {
            MainUtils.printHelpVarArgs(ALL_FLAGS, "input", "output");
            return;
        }

        sink.init();
        Transcoder transcoder = builder.create();
        transcoder.transcode();
    }

but when I have a try,I got error:

[mp3demuxer] Skipped 593 bytes of junk
[mp3demuxer] Skipped 194 bytes of junk
No frames output.
Exception in thread "main" java.lang.NullPointerException
	at org.jcodec.common.model.Picture.createCropped(Picture.java:80)
	at org.jcodec.common.model.Picture.create(Picture.java:75)
	at org.jcodec.api.transcode.PixelStoreImpl.getPicture(PixelStoreImpl.java:21)
	at org.jcodec.api.transcode.filters.ColorTransformFilter.filter(ColorTransformFilter.java:34)
	at org.jcodec.api.transcode.Transcoder$Stream.filterFrame(Transcoder.java:162)
	at org.jcodec.api.transcode.Transcoder$Stream.finalFlushQueues(Transcoder.java:196)
	at org.jcodec.api.transcode.Transcoder.transcode(Transcoder.java:402)
	at com.fang.dsp.utils.MyTranscodeMain.main(MyTranscodeMain.java:252)

Please help me,I think something is not right when I config the Builder.

Thanks a lot!

**Comment by TheComputerizer** [comment]
Hello, did you ever figure out your issue here? I am running into similar problems

**Comment by svitvitskiy** [comment]
Hi, could you please post the exact code snippet as well as your source files?

**Comment by TheComputerizer** [comment]
Sure, I use this test method, where "input" points to [this video](https://streamable.com/6nzmhv) (As a downloaded file, not a URL), and "output" is a wav file of the same name. My goal is to extract the audio from my mp4 and save it to the wav file.

It usually gives me a "Video encoder has not been initialized" message, but am I not already calling `sink.init()`?

```
private static void test(String input, String output) {
        try {
            Transcoder.TranscoderBuilder builder = Transcoder.newTranscoder();
            Format inputVideoFormat = Format.MOV;
            Tuple._3<Integer, Integer, Codec> inputCodecVideo = selectSuitableTrack(input, inputVideoFormat, TrackType.VIDEO);
            Source sourceVideo = new SourceImpl(input, inputVideoFormat, inputCodecVideo, inputCodecVideo);
            sourceVideo.setOption(Options.PROFILE, "default");
            sourceVideo.setOption(Options.INTERLACED, false);
            builder.addSource(sourceVideo);
            builder.setSeekFrames(0, 0).setMaxFrames(0, Integer.MAX_VALUE);

            Sink sink = new SinkImpl(output, Format.WAV, Codec.H264, Codec.PCM);
            builder.addSink(sink);
            builder.setAudioMapping(0, 0, false);
            builder.setVideoMapping(0, 0, false);

            builder.addFilter(0, new DumpMvFilter(true));
            sink.init();
            builder.create().transcode();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    ```
