### ISSUE TITLE
MPEG2 decode

### ISSUE THREAD

**Issue by B-R-Bender** [jcodec/jcodec#405]
Hey guys, I think you are awesome and appreciate your work!
Can you, please, guide me with jcodec usage?
I've try some siple code to decode mpeg2 video

    public class JaPlayer {
    
        MPEGDecoder mpegDecoder = new MPEGDecoder();
        File file = new File("src/main/resources/rec20srtvi.mpg");
    
    
        public JaPlayer() throws IOException, JCodecException, InterruptedException {
            MPSMediaInfo mpsMediaInfo = new MPSMediaInfo();
            List<MPSMediaInfo.MPEGTrackMetadata> mediaInfo = mpsMediaInfo.getMediaInfo(file);
    
            DrawImageOnCanvas drawImageOnCanvas = new DrawImageOnCanvas();
            drawImageOnCanvas.init("test", 544, 480);
    
            byte[][] data = new byte[][]{new byte[261120], new byte[261120], new byte[261120]};
    
            MPEGES mpeges = new MPEGES(Channels.newChannel(new FileInputStream(file)), 4056);
    
            while (true) {
                MPEGPacket frame = mpeges.getFrame();
                if (frame == null) {
                    break;
                }
    
                mpegDecoder.decodeFrame(frame.getData(), data);
                drawImageOnCanvas.paint(data);
            }
        }
    }

But I've got these errors:

    java.lang.RuntimeException: Invalid code prefix 0000000000000000
	at org.jcodec.common.io.VLC.readVLC(VLC.java:119)
	at org.jcodec.common.io.VLCBuilder$1.readVLC(VLCBuilder.java:57)
	at org.jcodec.codecs.mpeg12.MPEGDecoder.blockIntra(MPEGDecoder.java:626)
	at org.jcodec.codecs.mpeg12.MPEGDecoder.decodeMacroblock(MPEGDecoder.java:463)
	at org.jcodec.codecs.mpeg12.MPEGDecoder.decodeSlice(MPEGDecoder.java:313)
	at org.jcodec.codecs.mpeg12.MPEGDecoder.doDecodeSlice(MPEGDecoder.java:260)
	at org.jcodec.codecs.mpeg12.MPEGDecoder.decodePicture(MPEGDecoder.java:231)
	at org.jcodec.codecs.mpeg12.MPEGDecoder.decodeFrame(MPEGDecoder.java:113)
	at ru.bender.jplayer.JaPlayer.<init>(JaPlayer.java:43)
	at ru.bender.jplayer.JPlayerTest.testPlayer(JPlayerTest.java:25)
	at ru.bender.jplayer.JPlayerTest.main(JPlayerTest.java:15)
    
    Exception in thread "main" java.lang.RuntimeException: Unexpected start code 192
	at org.jcodec.codecs.mpeg12.MPEGDecoder.decodePicture(MPEGDecoder.java:233)
	at org.jcodec.codecs.mpeg12.MPEGDecoder.decodeFrame(MPEGDecoder.java:113)
	at ru.bender.jplayer.JaPlayer.<init>(JaPlayer.java:43)
	at ru.bender.jplayer.JPlayerTest.testPlayer(JPlayerTest.java:25)
	at ru.bender.jplayer.JPlayerTest.main(JPlayerTest.java:15)

Can you please provide/suggest a solution?
Thank you.
Regards!

**Comment by svitvitskiy** [comment]
Try to see if your file works in TranscodeMain. My guess is you need to be
using MPSDemexer (MPEG Program Stream). TranscodeMain will autodetect
format using demuxer’s ‘probe’ function.

If you find that TranscodeMain works, try to work out the exact sequence of
thing it does in order to process the file.

If not, let us know. We can take a look.

Stan
