### ISSUE TITLE
how to decode h264 byte[] to BufferedImage

### ISSUE THREAD

**Issue by nicevibesplus** [jcodec/jcodec#406]
I am receiving a byte[] for every frame of a video stream and want to decode it to a BufferedImage. This is my code for now:

    private H264Decoder decoder = new H264Decoder();
	private ByteBuffer bb = null;
	private Picture out = Picture.create(960, 720, ColorSpace.YUV420);

	private void decode(byte[] data) {
		System.out.println("decoding");
		bb = ByteBuffer.wrap(data);
		Picture real = decoder.decodeFrame(bb, out.getData());
		BufferedImage bi = AWTUtil.toBufferedImage(real);
         }

But this is the error message I get: 

> Exception in thread "Thread-1" java.lang.NullPointerException
	at org.jcodec.scale.AWTUtil.toBufferedImage(AWTUtil.java:28)
	at TelloCameraThread.decode(TelloCameraThread.java:88)
	at TelloCameraThread.run(TelloCameraThread.java:62)

Help appreciated.

nvplus

**Comment by mondain** [comment]
Your Picture `out` may need to be in the `ColorSpace.420J` color space, but that's just a guess based on my use of the encoder.
