### ISSUE TITLE
ArrayIndexOutOfBoundsException SliceDecoder.java:200

### ISSUE THREAD

**Issue by backinside** [jcodec/jcodec#413]
I'm decoding raw h264 nal units, and I have to create the byte buffer for the decoder larger to prevent the exception
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException
	at org.jcodec.codecs.h264.decode.SliceDecoder.putMacroblock(SliceDecoder.java:200)
	at org.jcodec.codecs.h264.decode.SliceDecoder.decodeMacroblocks(SliceDecoder.java:104)
	at org.jcodec.codecs.h264.decode.SliceDecoder.decodeFromReader(SliceDecoder.java:73)
	at org.jcodec.codecs.h264.H264Decoder$FrameDecoder.decodeFrame(H264Decoder.java:153)
	at org.jcodec.codecs.h264.H264Decoder.decodeFrameFromNals(H264Decoder.java:104)
	at org.jcodec.codecs.h264.H264Decoder.decodeFrame(H264Decoder.java:100)
In the debugger, I can see that mby16 is already 1072 with i = 8 * stride = 1920

the byte array that triggers it

[jcodecbytearray.zip](https://github.com/jcodec/jcodec/files/4590197/jcodecbytearray.zip)

**Comment by svitvitskiy** [comment]
Thanks, I'll take a look.
