### ISSUE TITLE
FrameGrab Can't detect format of MP4 after being resized with ffmpeg

### ISSUE THREAD

**Issue by TheStonedTurtle** [jcodec/jcodec#421]
I'm creating a program that opens an MP4 file and returns the next frame as a BufferedImage upon request (Pretty much viewing an MP4 frame by frame).

My code is working fine on my original test MP4 but if I resize that MP4 using `ffmpeg` i get a 

```
org.jcodec.api.UnsupportedFormatException: Could not detect the format of the input video.
	at org.jcodec.api.FrameGrab.createFrameGrab(FrameGrab.java:55)
```

Resize Command:
```
ffmpeg -i input.mp4 -s 1280x720 output.mp4
```

Code:
```java
final FileChannelWrapper wrapper = NIOUtils.readableChannel(_FILE_);
final FrameGrab grab = FrameGrab.createFrameGrab(wrapper);
```

I'm pretty new to jcodec and media encoding/decoding in general so I'm not sure if this is a problem with my resize command, my code, or the library.

**Comment by svitvitskiy** [comment]
Could you attach a sample file so I can reproduce? Thanks.

**Comment by TheStonedTurtle** [comment]
> 
> 
> Could you attach a sample file so I can reproduce? Thanks.

I uploaded it to my google drive, let me know if you need me to use another file hosting service.

https://drive.google.com/file/d/1O3L3pu8yBnvmlu8vuIXdiN6JX6te_zOL/view?usp=sharing

**Comment by svitvitskiy** [comment]
Seems to be working with HEAD jcodec. Pull the latest HEAD. Try 
```
java -cp "jcodec.jar:jcodec-samples.jar" org.jcodec.samples.api.FrameGrabDemo -n 100 input.mp4 
```
It should generate 100 images into your home folder.

**Comment by TheStonedTurtle** [comment]
Just to clarify, I sent you the original MP4 so you would need to resize the MP4 using the ffmpeg I mentioned in the original post. If you were requesting the resized version I apologize, and it can be found here: https://drive.google.com/file/d/14pACyqz8CjtG-dc7_NFbSfMMY9j1MbSu/view?usp=sharing

I will try what you've suggested with the resized version and report back shortly.

**Comment by TheStonedTurtle** [comment]
> Seems to be working with HEAD jcodec. Pull the latest HEAD. Try

Well I feel stupid but I'm not sure what you want me to do here. I'm using maven to add the jcodec dependencies for my project. Do you want me to clone this repo and compile the .jar from the current HEAD?

**Comment by svitvitskiy** [comment]
Yes, HEAD is whatever you clone from git.
```
git clone https://github.com/jcodec/jcodec.git
(cd jcodec; mvn clean install)
(cd jcodec/javase; mvn clean install)
(cd jcodec/samples; mvn clean install)
java -cp "jcodec/target/jcodec-0.2.6-SNAPSHOT.jar:jcodec/javase/target/jcodec-javase-0.2.6-SNAPSHOT.jar:jcodec/samples/target/jcodec-samples-0.2.6-SNAPSHOT.jar" org.jcodec.samples.api.FrameGrabDemo -n 100 output.mp4
```
All the latest bugfixes are usually in HEAD. The latest version from maven is sometimes 6 months old.

**Comment by TheStonedTurtle** [comment]
Running `mvn clean install` on my clone of the repo is giving me the below test failure.

```
Running org.jcodec.movtool.MetadataEditorTest
[INFO]	. (:0):	Relocating movie header to the end of the file.
[INFO]	. (:0):	Relocating movie header to the end of the file.
Tests run: 5, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.133 sec <<< FAILURE!
testKeyedWriteSlow(org.jcodec.movtool.MetadataEditorTest)  Time elapsed: 0.044 sec  <<< ERROR!
java.lang.NullPointerException
	at org.jcodec.movtool.MetadataEditorTest.keyedWriteSub(MetadataEditorTest.java:82)
	at org.jcodec.movtool.MetadataEditorTest.testKeyedWriteSlow(MetadataEditorTest.java:56)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
```

**Comment by svitvitskiy** [comment]
I am not sure, doesn't happen on my machine.

As an alternative, try importing all jcodec, jcodec-javase, jcodec-samples into your Eclipse or IntelliJ as maven projects. Then simply run the class FrameGrabDemo.
