### ISSUE TITLE
FrameGrab.createFrameGrab(NIOUtils.readableChannel(new File())) gives "java.lang.IllegalArgumentException: Not a video track" for some MP4 files

### ISSUE THREAD

**Issue by s3433557** [jcodec/jcodec#453]
`FrameGrab.createFrameGrab(NIOUtils.readableChannel(new File(uri.getPath())))` gives `java.lang.IllegalArgumentException: Not a video track` for some files:

```
java.lang.IllegalArgumentException: Not a video track
        at org.jcodec.containers.mp4.boxes.TrakBox.getCodedSize(TrakBox.java:269)
        at org.jcodec.containers.mp4.demuxer.MP4DemuxerTrackMeta.fromTrack(MP4DemuxerTrackMeta.java:58)
        at org.jcodec.containers.mp4.demuxer.AbstractMP4DemuxerTrack.getMeta(AbstractMP4DemuxerTrack.java:242)
        at org.jcodec.api.FrameGrab.detectDecoder(FrameGrab.java:212)
        at org.jcodec.api.FrameGrab.createFrameGrab(FrameGrab.java:69)
```

uri is obtained by `Activity.getIntent().getData()` method from file chooser or from file explorer where I choose the file I had from android device.

For example, a video recorded from [Open Camera](https://play.google.com/store/apps/details?id=net.sourceforge.opencamera&hl=en&gl=US) app at 1280x720 resolution on phone Samsung Galaxy S8 Android version 9.

https://user-images.githubusercontent.com/20717627/103517326-0a67d480-4ec6-11eb-829f-5369d76f69f2.mp4

**Comment by thhart** [comment]
Hello, I can confirm the same problem, it looks to me the video track is in an unknown format. The error is at a place where meta information is extracted from it like width and height. Unfortunately I can not see this in this track information there albeit it is marked as video track. Do you have any hint how to resolve this? Is this a common problem, I would like to investigate but am rather new to this, so any hint could be helpful?

**Comment by marcelcamporelli** [comment]
Same here -- I created a test project to provide some failing cases:

https://github.com/BrickworkVentures/jcodec-test

For someone familiar with the jcodec code, it may be easy to fix it. Not for me though...

**Comment by kanakharaharsh** [comment]
I am facing the same issue. Is the issue resolved?

**Comment by meteorOSS** [comment]
I also encountered this problem, is there any solution?

When I use the following video

https://github.com/user-attachments/assets/13ab9171-b4eb-4b4d-949f-b07aa0b828f2

**Comment by meteorOSS** [comment]
I ended up using javacv
It uses ffmpeg, which takes up a lot more space...

**Comment by kanakharaharsh** [comment]
I ended up using MPlayer. Much easier to use, and it works with almost all types of image/video/audio content.
