### ISSUE TITLE
Unable to decode MKV h.264 video frames

### ISSUE THREAD

**Issue by TeofilisMartisius** [jcodec/jcodec#466]
Hi,

I'm trying to decode this video using code similar to example here: https://github.com/jcodec/jcodec/blob/master/src/test/java/org/jcodec/containers/mkv/MKVFrameReadingTest.java

I'm getting:

```
WARNING: unspecified ebml ID (0x55 0xb0 ) encountered at position 0x185
Unspecified header: 0x55 0xb0  at 389
Exception in thread "main" java.lang.IllegalStateException
	at org.jcodec.common.Preconditions.checkState(Preconditions.java:424)
	at org.jcodec.codecs.h264.mp4.AvcCBox.parse(AvcCBox.java:77)
	at org.jcodec.codecs.h264.mp4.AvcCBox.parseAvcCBox(AvcCBox.java:44)
	at xxx.DecodeVideoBug.main(DecodeVideoBug.java:25)
```

My code and test file attached. The test file has been produced using ffmpeg using libx264, via "ffmpeg -i out.mkv -vcodec libx264 out2.mkv", so I'm assuming the video is not broken? It can be played using usual video players. 

I'm using jcodec v0.2.5 on OpenJDK 16 on Linux.

Sincerely,
Teofilis Martisius
[out2.mkv.gz](https://github.com/jcodec/jcodec/files/6964359/out2.mkv.gz)
[DecodeVideoBug.java.txt](https://github.com/jcodec/jcodec/files/6964364/DecodeVideoBug.java.txt)

**Comment by karen-hikesupport** [comment]
Yes I getting the same issue with jcodec parse "AvcCBox.parseAvcCBox'
