### ISSUE TITLE
[Help] Can anyone tell me how to extract frame from Webm video files?

### ISSUE THREAD

**Issue by Paper-Folding** [jcodec/jcodec#469]
I just get this UnsupportedFormatException while grabbing frame from webm files, but I see some code of webm in this project. Can anyone help me how to do it? Or where is the docs is?
```log
Exception in thread "main" org.jcodec.api.UnsupportedFormatException: Could not detect the format of the input video.
	at org.jcodec.api.FrameGrab.createFrameGrab(FrameGrab.java:55)
	at org.jcodec.api.FrameGrab.getFrameFromFile(FrameGrab.java:295)
	at Main.main(Main.java:13)
```

**Comment by Paper-Folding** [comment]
Resolved with javacv.
