### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by SmallGolem** [jcodec/jcodec#500]
Hello,
Good morning,
this code produces a big memory leak but I don't store massive objects yet
```java
FrameGrab grab = FrameGrab.createFrameGrab(NIOUtils.readableChannel(new File("video.mp4")));
int frameCount = grab.getVideoTrack().getMeta().getTotalFrames();
Image[] frames = new Image[frameCount];
for (int i = 0; i < frameCount; i++) {
    frames[i] = new ImageIcon(AWTUtil.toBufferedImage(grab.getNativeFrame())).getImage();
}
```
So this code returns an OutOfMemory
```cmd
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at java.desktop/java.awt.image.DataBufferByte.<init>(DataBufferByte.java:77)
	at java.desktop/java.awt.image.Raster.createInterleavedRaster(Raster.java:310)
	at java.desktop/java.awt.image.BufferedImage.<init>(BufferedImage.java:376)
	at org.jcodec.scale.AWTUtil.toBufferedImage(AWTUtil.java:40)
	at Test.main(Test.java:17)
```

**Comment by svitvitskiy** [comment]
Well, if I read it correctly, you basically storing the entire uncompressed video in memory. Depending on the frame count and resolution this can take quite a lot of memory.
