### ISSUE TITLE
mp4 file can't share to instagram

### ISSUE THREAD

**Issue by bearprada** [jcodec/jcodec#55]
i using `SequenceEncoder` to output mp4 file(frame rate : 5fps, total time : 5 sec, resolution : 640x640). but it cannot share to instagram. the error message show as follow(instagram)

```
08-26 16:28:42.213    9084-9815/? E/StreamingApiRequestLoaderCallbacks﹕ Caught exception performing/parsing streaming request
    java.lang.NullPointerException
            at com.instagram.feed.d.l.a(Media.java:934)
            at com.instagram.feed.a.a.a(MediaFeedRequest.java:116)
            at com.instagram.c.k.p.u(StreamingApiRequestLoaderCallbacks.java:117)
            at com.instagram.c.k.p.d(StreamingApiRequestLoaderCallbacks.java:46)
            at android.support.v4.a.a.e(AsyncTaskLoader.java:242)
            at android.support.v4.a.b.e(AsyncTaskLoader.java:51)
            at android.support.v4.a.b.b(AsyncTaskLoader.java:40)
            at android.support.v4.a.k.call(ModernAsyncTask.java:123)
            at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
            at java.util.concurrent.FutureTask.run(FutureTask.java:137)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
            at java.lang.Thread.run(Thread.java:856)
```

**Comment by svitvitskiy** [comment]
I am sorry, could you provide exact stand-alone test case that reproduces the problem in isolation?
