### ISSUE TITLE
Getting "long term" RuntimeException when decoding frame on a AVCC stream

### ISSUE THREAD

**Issue by robertoandrade** [jcodec/jcodec#65]
I'm getting the following exception when trying to extract a series of frames from an H264/AVCC stream originating from an iOS device:

``` java
java.lang.RuntimeException: long term
    at org.jcodec.codecs.h264.decode.SliceDecoder.reorder(SliceDecoder.java:396)
    at org.jcodec.codecs.h264.decode.SliceDecoder.buildRefListP(SliceDecoder.java:303)
    at org.jcodec.codecs.h264.decode.SliceDecoder.decode(SliceDecoder.java:205)
    at org.jcodec.codecs.h264.H264Decoder$FrameDecoder.decodeFrame(H264Decoder.java:87)
    at org.jcodec.codecs.h264.H264Decoder.decodeFrame(H264Decoder.java:61)
...
```

By looking at the code, it looks like that was left as a `TODO` for later?

``` java
private void reorder(Picture[] result, int list) {
        if (sh.refPicReordering[list] == null)
            return;

        int predict = sh.frame_num;
        int maxFrames = 1 << (sh.sps.log2_max_frame_num_minus4 + 4);

        for (int ind = 0; ind < sh.refPicReordering[list][0].length; ind++) {
            switch (sh.refPicReordering[list][0][ind]) {
            case 0:
                predict = wrap(predict - sh.refPicReordering[list][1][ind] - 1, maxFrames);
                break;
            case 1:
                predict = wrap(predict + sh.refPicReordering[list][1][ind] + 1, maxFrames);
                break;
            case 2:
                throw new RuntimeException("long term");
            }
            for (int i = numRef[list] - 1; i > ind; i--)
                result[i] = result[i - 1];
            result[ind] = sRefs[predict];
            for (int i = ind + 1, j = i; i < numRef[list] && result[i] != null; i++) {
                if (result[i] != sRefs[predict])
                    result[j++] = result[i];
            }
        }
    }
```

**Comment by robertoandrade** [comment]
Wondering how much of that missing implementation has to do with the following snipped I extracted from [ffmpeg](https://ffmpeg.mplayerhq.hu/doxygen/2.2/h264_8c_source.html#l03964) source and the respondent calling functions [ff_pred_weight_table](https://ffmpeg.mplayerhq.hu/doxygen/2.2/h264_8c_source.html#l02687) and [implicit_weight_table](https://ffmpeg.mplayerhq.hu/doxygen/2.2/h264_8c_source.html#l02754):

```C
 3964     if ((h->pps.weighted_pred && h->slice_type_nos == AV_PICTURE_TYPE_P) ||
 3965         (h->pps.weighted_bipred_idc == 1 &&
 3966          h->slice_type_nos == AV_PICTURE_TYPE_B))
 3967         ff_pred_weight_table(h);
 3968     else if (h->pps.weighted_bipred_idc == 2 &&
 3969              h->slice_type_nos == AV_PICTURE_TYPE_B) {
 3970         implicit_weight_table(h, -1);
 3971     } else {
 3972         h->use_weight = 0;
 3973         for (i = 0; i < 2; i++) {
 3974             h->luma_weight_flag[i]   = 0;
 3975             h->chroma_weight_flag[i] = 0;
 3976         }
 3977     }
```

**Comment by svitvitskiy** [comment]
This has to do with long term reference picture which (as I used to believe) is never used.

Could you provide a sample file so that I can fix and test?

**Comment by dhrumilsheth9** [comment]
I am getting the same error, did anyone find a solution?
