### ISSUE TITLE
ArrayIndexOutOfBoundsException when using P-Frames

### ISSUE THREAD

**Issue by mrieser** [jcodec/jcodec#86]
Simple way to reproduce: Using `org.jcodec.samples.gen.SequenceEncoderDemo`, changing the size of the BufferedImages from 640x480 to 800x600 results in the following exception:
```java
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 480000
	at org.jcodec.codecs.h264.encode.MBEncoderHelper.takeSafe(MBEncoderHelper.java:40)
	at org.jcodec.codecs.h264.encode.MBEncoderP16x16.mvEstimate(MBEncoderP16x16.java:145)
	at org.jcodec.codecs.h264.encode.MBEncoderP16x16.encodeMacroblock(MBEncoderP16x16.java:70)
	at org.jcodec.codecs.h264.H264Encoder.encodeMacroblock(H264Encoder.java:301)
	at org.jcodec.codecs.h264.H264Encoder.encodeSlice(H264Encoder.java:279)
	at org.jcodec.codecs.h264.H264Encoder.encodeFrame(H264Encoder.java:170)
	at org.jcodec.codecs.h264.H264Encoder.encodeFrame(H264Encoder.java:107)
	at org.jcodec.codecs.h264.H264Encoder.encodeFrame(H264Encoder.java:92)
	at org.jcodec.api.SequenceEncoder.encodeNativeFrame(SequenceEncoder.java:80)
	at org.jcodec.api.awt.SequenceEncoder.encodeImage(SequenceEncoder.java:23)
	at org.jcodec.samples.gen.SequenceEncoderDemo.main(SequenceEncoderDemo.java:59)
```
I would assume that P-Frames / KeyInterval should work more or less independent of the movie resolution.

**Comment by svitvitskiy** [comment]
Fixed
